shadow$provide.module$bfuncs$ExpressionInput=function(global,require,module,exports){function _typeof(obj$jscomp$0){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&"function"===typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};return _typeof(obj$jscomp$0)}function _getRequireWildcardCache(nodeInterop){if("function"!==typeof WeakMap)return null;var cacheBabelInterop=
new WeakMap,cacheNodeInterop=new WeakMap;return(_getRequireWildcardCache=function(nodeInterop){return nodeInterop?cacheNodeInterop:cacheBabelInterop})(nodeInterop)}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||!1;descriptor.configurable=!0;"value"in descriptor&&(descriptor.writable=!0);Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){protoProps&&
_defineProperties(Constructor.prototype,protoProps);staticProps&&_defineProperties(Constructor,staticProps);return Constructor}function _inherits(subClass,superClass){if("function"!==typeof superClass&&null!==superClass)throw new TypeError("Super expression must either be null or a function");subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,writable:!0,configurable:!0}});superClass&&_setPrototypeOf(subClass,superClass)}function _setPrototypeOf(o,p){_setPrototypeOf=
Object.setPrototypeOf||function(o,p){o.__proto__=p;return o};return _setPrototypeOf(o,p)}function _createSuper(Derived){var hasNativeReflectConstruct=_isNativeReflectConstruct();return function(){var Super=_getPrototypeOf(Derived);if(hasNativeReflectConstruct){var NewTarget=_getPrototypeOf(this).constructor;Super=Reflect.construct(Super,arguments,NewTarget)}else Super=Super.apply(this,arguments);Super=!Super||"object"!==_typeof(Super)&&"function"!==typeof Super?_assertThisInitialized(this):Super;
return Super}}function _assertThisInitialized(self){if(void 0===self)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return self}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}function _getPrototypeOf(o$jscomp$0){_getPrototypeOf=Object.setPrototypeOf?
Object.getPrototypeOf:function(o){return o.__proto__||Object.getPrototypeOf(o)};return _getPrototypeOf(o$jscomp$0)}function _defineProperty(obj,key,value){key in obj?Object.defineProperty(obj,key,{value,enumerable:!0,configurable:!0,writable:!0}):obj[key]=value;return obj}function _createForOfIteratorHelper(o,allowArrayLike){var it="undefined"!==typeof Symbol&&o[Symbol.iterator]||o["@@iterator"];if(!it){if(Array.isArray(o)||(it=_unsupportedIterableToArray(o))||allowArrayLike&&o&&"number"===typeof o.length){it&&
(o=it);var i=0;allowArrayLike=function(){};return{s:allowArrayLike,n:function(){return i>=o.length?{done:!0}:{done:!1,value:o[i++]}},e:function(_e){throw _e;},f:allowArrayLike}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}var normalCompletion=!0,didErr=!1,err;return{s:function(){it=it.call(o)},n:function(){var step=it.next();normalCompletion=step.done;return step},e:function(_e2){didErr=
!0;err=_e2},f:function(){try{if(!normalCompletion&&null!=it["return"])it["return"]()}finally{if(didErr)throw err;}}}}function _toConsumableArray(arr){var JSCompiler_temp=Array.isArray(arr)?_arrayLikeToArray(arr):void 0;JSCompiler_temp||(JSCompiler_temp="undefined"!==typeof Symbol&&null!=arr[Symbol.iterator]||null!=arr["@@iterator"]?Array.from(arr):void 0);if(!(arr=JSCompiler_temp||_unsupportedIterableToArray(arr)))throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
return arr}function _unsupportedIterableToArray(o,minLen){if(o){if("string"===typeof o)return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);"Object"===n&&o.constructor&&(n=o.constructor.name);if("Map"===n||"Set"===n)return Array.from(o);if("Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}}function _arrayLikeToArray(arr,len){if(null==len||len>arr.length)len=arr.length;for(var i=0,arr2=Array(len);i<len;i++)arr2[i]=
arr[i];return arr2}function getExprParseData(state){var errRanges=new _rangeset.RangeSetBuilder,vars=new Set,stack=[];(0,_language.syntaxTree)(state).iterate({enter:function(nt,from,to){if(nt.isError)from===to?from?errRanges.add(from-1,to,zeroWidthErrorRightMark):errRanges.add(from,to+1,zeroWidthErrorLeftMark):errRanges.add(from,to,errorMark),stack.push(Object.assign([],{operation:"ERROR"}));else if(nt.is("str"))stack.push(Object.assign([],{operation:nt.name}));else{if(nt.is("atom")){var stackTop=
stack[stack.length-1];switch(nt.name){case "TRUE":stackTop.push(!0);break;case "FALSE":stackTop.push(!1);break;case "var":nt=state.sliceDoc(from,to);stackTop.push(nt);vars.add(nt);break;default:console.warn("Unknown atom "+nt.name)}}return!1}},leave:function(nt){nt.is("atom")||(nt=stack[stack.length-2])&&nt.push(stack.pop())}});var errMarks=errRanges.finish();return{parse:stack.pop(),vars:_toConsumableArray(vars).sort(),errors:!!errMarks.size,errMarks}}function getTermsParseData(state){var errRanges=
new _rangeset.RangeSetBuilder,terms=new Set,duplicates=!1;(0,_language.syntaxTree)(state).iterate({enter:function(nt,from,to){if(nt.isError)from===to?from?errRanges.add(from-1,to,zeroWidthErrorRightMark):errRanges.add(from,to+1,zeroWidthErrorLeftMark):errRanges.add(from,to,errorMark);else if(nt.is("term")){nt=state.sliceDoc(from,to);var termVal=Number.parseInt(nt);termVal>Number.MAX_SAFE_INTEGER&&(termVal=BigInt(nt));terms.has(termVal)?(duplicates=!0,errRanges.add(from,to,duplicateTermMark)):terms.add(termVal)}}});
var errMarks=errRanges.finish();return{terms,errors:!!errMarks.size,duplicates,errMarks}}function getVariableMarks(state){var mVar=state.field(markedVariableField),ranges=new _rangeset.RangeSetBuilder;(0,_language.syntaxTree)(state).iterate({enter:function(nt,from,to){"var"===nt.name&&state.sliceDoc(from,to)===mVar&&ranges.add(from,to,varMark);return nt.isError||nt.is("str")?void 0:!1}});return ranges.finish()}Object.defineProperty(exports,"__esModule",{value:!0});exports["default"]=void 0;var _react=
function(obj,nodeInterop){if(!nodeInterop&&obj&&obj.__esModule)return obj;if(null===obj||"object"!==_typeof(obj)&&"function"!==typeof obj)return{"default":obj};if((nodeInterop=_getRequireWildcardCache(nodeInterop))&&nodeInterop.has(obj))return nodeInterop.get(obj);var newObj={},hasPropertyDescriptor=Object.defineProperty&&Object.getOwnPropertyDescriptor,key;for(key in obj)if("default"!==key&&Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,
key):null;desc&&(desc.get||desc.set)?Object.defineProperty(newObj,key,desc):newObj[key]=obj[key]}newObj["default"]=obj;nodeInterop&&nodeInterop.set(obj,newObj);return newObj}(require("module$node_modules$react$index")),_state=require("module$node_modules$$codemirror$state$dist$index_cjs"),_view=require("module$node_modules$$codemirror$view$dist$index_cjs"),_rangeset=require("module$node_modules$$codemirror$rangeset$dist$index_cjs"),_matchbrackets=require("module$node_modules$$codemirror$matchbrackets$dist$index_cjs"),
_highlight=require("module$node_modules$$codemirror$highlight$dist$index_cjs"),_language=require("module$node_modules$$codemirror$language$dist$index_cjs");global=require("module$bfuncs$bexprParser");module=require("module$bfuncs$termsParser");var _clsx=function(obj){return obj&&obj.__esModule?obj:{"default":obj}}(require("module$node_modules$clsx$dist$clsx")),varMark=_view.Decoration.mark({"class":"cm-markedVar"}),errorMark=_view.Decoration.mark({"class":"cm-parseError"}),zeroWidthErrorLeftMark=
_view.Decoration.mark({"class":"cm-zeroWidthErrorLeft"}),zeroWidthErrorRightMark=_view.Decoration.mark({"class":"cm-zeroWidthErrorRight"}),duplicateTermMark=_view.Decoration.mark({"class":"cm-duplicateTerm"});require=_highlight.Tag.define(_highlight.tags.integer);var octInt=_highlight.Tag.define(_highlight.tags.integer),binInt=_highlight.Tag.define(_highlight.tags.integer),hstyle=_highlight.HighlightStyle.define([{tag:_highlight.tags.compareOperator,"class":"cmt-rel-op"},{tag:_highlight.tags.operatorKeyword,
"class":"cmt-operator-keyword cmt-operator"},{tag:_highlight.tags.logicOperator,"class":"cmt-log-op"},{tag:_highlight.tags.special(_highlight.tags.logicOperator),"class":"cmt-negated"},{tag:_highlight.tags.integer,"class":"cmt-integer"},{tag:require,"class":"cmt-hex"},{tag:octInt,"class":"cmt-oct"},{tag:binInt,"class":"cmt-bin"},{tag:_highlight.tags.separator,"class":"cmt-sep"}]),termsLanguage=_language.LezerLanguage.define({parser:module.parser.configure({props:[(0,_highlight.styleTags)({DEC:_highlight.tags.integer,
BIN:binInt,OCT:octInt,HEX:require,sep:_highlight.tags.separator})]})}),bexprLanguage=_language.LezerLanguage.define({parser:global.parser.configure({props:[(0,_highlight.styleTags)({lit:_highlight.tags.bool,litKey:[_highlight.tags.keyword,_highlight.tags.bool],log:_highlight.tags.logicOperator,logKey:[_highlight.tags.operatorKeyword,_highlight.tags.logicOperator],rel:_highlight.tags.compareOperator,relKey:[_highlight.tags.operatorKeyword,_highlight.tags.compareOperator],not:_highlight.tags.special(_highlight.tags.logicOperator),
notKey:[_highlight.tags.operatorKeyword,_highlight.tags.special(_highlight.tags.logicOperator)],"var":_highlight.tags.variableName,neg:_highlight.tags.special(_highlight.tags.logicOperator)})]})}),changeMarkedVariable=_state.StateEffect.define(),changeShowErrors=_state.StateEffect.define(),showErrorsField=_state.StateField.define({create:function(){return!1},update:function(value,tr){tr=_createForOfIteratorHelper(tr.effects);var _step;try{for(tr.s();!(_step=tr.n()).done;){var e=_step.value;if(e.is(changeShowErrors))return e.value}}catch(err){tr.e(err)}finally{tr.f()}return value}}),
markedVariableField=_state.StateField.define({create:function(){return null},update:function(value,tr){tr=_createForOfIteratorHelper(tr.effects);var _step2;try{for(tr.s();!(_step2=tr.n()).done;){var e=_step2.value;if(e.is(changeMarkedVariable))return e.value}}catch(err){tr.e(err)}finally{tr.f()}return value}});global=function(_Component){function ExpressionInput(props){if(!(this instanceof ExpressionInput))throw new TypeError("Cannot call a class as a function");var _this=_super.call(this,props);
_defineProperty(_assertThisInitialized(_this),"divRef",void 0);_defineProperty(_assertThisInitialized(_this),"createEditor",function(mode,doc){var parseField=_state.StateField.define({create:function(state){return _this.parse(state)},update:function(prevData,tr){return tr.docChanged?_this.parse(tr.state):prevData}}),extensions=[hstyle.extension,_highlight.classHighlightStyle.extension,(0,_view.drawSelection)(),parseField,showErrorsField,_view.EditorView.lineWrapping,_view.EditorView.decorations.compute([showErrorsField,
parseField],function(state){return state.field(showErrorsField)?state.field(parseField).errMarks:_view.Decoration.none})];switch(mode){case "expression":extensions.push(new _language.LanguageSupport(bexprLanguage),markedVariableField,_view.EditorView.decorations.compute(["doc",markedVariableField],getVariableMarks),(0,_matchbrackets.bracketMatching)());break;case "terms":extensions.push(new _language.LanguageSupport(termsLanguage));break;default:throw Error("mode must be 'terms' or 'expression'");
}return new _view.EditorView({state:_state.EditorState.create({extensions,doc})})});_defineProperty(_assertThisInitialized(_this),"parse",function(state){a:switch(_this.props.mode){case "terms":var pd=getTermsParseData(state);break a;case "expression":pd=getExprParseData(state);break a;default:throw Error("mode must be 'terms' or 'expression'");}var rest=pd;var excluded=["errMarks"];if(null==rest)rest={};else{if(null==rest)var target={};else{target={};var sourceKeys=Object.keys(rest),i;for(i=0;i<
sourceKeys.length;i++){var key=sourceKeys[i];0<=excluded.indexOf(key)||(target[key]=rest[key])}}if(Object.getOwnPropertySymbols)for(i=Object.getOwnPropertySymbols(rest),key=0;key<i.length;key++)sourceKeys=i[key],0<=excluded.indexOf(sourceKeys)||Object.prototype.propertyIsEnumerable.call(rest,sourceKeys)&&(target[sourceKeys]=rest[sourceKeys]);rest=target}state=state.doc.toString();_this.props.onParse(state?Object.assign(rest,{text:state}):{errors:!0,text:state});return pd});_this.divRef=_react["default"].createRef();
_this.state={view:_this.createEditor(props.mode,props.defaultValue)};return _this}_inherits(ExpressionInput,_Component);var _super=_createSuper(ExpressionInput);_createClass(ExpressionInput,[{key:"componentDidUpdate",value:function(prevProps,prevState,snapshot){if(prevProps.mode!==this.props.mode)throw Error("Editor mode changed. Provide new key for new mode.");prevState=[];var _this$props=this.props;snapshot=_this$props.markedVariable;_this$props=_this$props.showErrors;snapshot!==prevProps.markedVariable&&
prevState.push(changeMarkedVariable.of(snapshot));_this$props!==prevProps.showErrors&&prevState.push(changeShowErrors.of(_this$props));prevState.length&&this.state.view.dispatch({effects:prevState})}},{key:"componentDidMount",value:function(){var _this$divRef$current;null===(_this$divRef$current=this.divRef.current)||void 0===_this$divRef$current?void 0:_this$divRef$current.append(this.state.view.dom)}},{key:"componentWillUnmount",value:function(){this.state.view.destroy()}},{key:"render",value:function(){return _react["default"].createElement("div",
{className:(0,_clsx["default"])("ExpressionInput","mode-".concat(this.props.mode),this.props.className),ref:this.divRef})}}]);return ExpressionInput}(_react.Component);_defineProperty(global,"defaultProps",{defaultValue:"",className:""});exports["default"]=global}
//# sourceMappingURL=module$bfuncs$ExpressionInput.js.map
