shadow$provide.module$bfuncs$FunctionSummary=function(global,require,module,exports){function _typeof(obj$jscomp$0){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&"function"===typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};return _typeof(obj$jscomp$0)}function _getRequireWildcardCache(nodeInterop){if("function"!==typeof WeakMap)return null;var cacheBabelInterop=
new WeakMap,cacheNodeInterop=new WeakMap;return(_getRequireWildcardCache=function(nodeInterop){return nodeInterop?cacheNodeInterop:cacheBabelInterop})(nodeInterop)}function _interopRequireWildcard(obj,nodeInterop){if(!nodeInterop&&obj&&obj.__esModule)return obj;if(null===obj||"object"!==_typeof(obj)&&"function"!==typeof obj)return{"default":obj};if((nodeInterop=_getRequireWildcardCache(nodeInterop))&&nodeInterop.has(obj))return nodeInterop.get(obj);var newObj={},hasPropertyDescriptor=Object.defineProperty&&
Object.getOwnPropertyDescriptor,key;for(key in obj)if("default"!==key&&Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,key):null;desc&&(desc.get||desc.set)?Object.defineProperty(newObj,key,desc):newObj[key]=obj[key]}newObj["default"]=obj;nodeInterop&&nodeInterop.set(obj,newObj);return newObj}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||
!1;descriptor.configurable=!0;"value"in descriptor&&(descriptor.writable=!0);Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){protoProps&&_defineProperties(Constructor.prototype,protoProps);staticProps&&_defineProperties(Constructor,staticProps);return Constructor}function _inherits(subClass,superClass){if("function"!==typeof superClass&&null!==superClass)throw new TypeError("Super expression must either be null or a function");subClass.prototype=
Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,writable:!0,configurable:!0}});superClass&&_setPrototypeOf(subClass,superClass)}function _setPrototypeOf(o,p){_setPrototypeOf=Object.setPrototypeOf||function(o,p){o.__proto__=p;return o};return _setPrototypeOf(o,p)}function _createSuper(Derived){var hasNativeReflectConstruct=_isNativeReflectConstruct();return function(){var Super=_getPrototypeOf(Derived);if(hasNativeReflectConstruct){var NewTarget=_getPrototypeOf(this).constructor;
Super=Reflect.construct(Super,arguments,NewTarget)}else Super=Super.apply(this,arguments);Super=!Super||"object"!==_typeof(Super)&&"function"!==typeof Super?_assertThisInitialized(this):Super;return Super}}function _assertThisInitialized(self){if(void 0===self)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return self}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;
try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}function _getPrototypeOf(o$jscomp$0){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(o){return o.__proto__||Object.getPrototypeOf(o)};return _getPrototypeOf(o$jscomp$0)}function _defineProperty(obj,key,value){key in obj?Object.defineProperty(obj,key,{value,enumerable:!0,configurable:!0,writable:!0}):obj[key]=value;return obj}function _slicedToArray(arr,i){var JSCompiler_temp=
Array.isArray(arr)?arr:void 0;if(!JSCompiler_temp)if(JSCompiler_temp=arr&&("undefined"!==typeof Symbol&&arr[Symbol.iterator]||arr["@@iterator"]),null==JSCompiler_temp)JSCompiler_temp=void 0;else{var _arr=[],_n=!0,_d=!1,_s;try{for(JSCompiler_temp=JSCompiler_temp.call(arr);!(_n=(_s=JSCompiler_temp.next()).done)&&(_arr.push(_s.value),!i||_arr.length!==i);_n=!0);}catch(err){_d=!0;var _e=err}finally{try{if(!_n&&null!=JSCompiler_temp["return"])JSCompiler_temp["return"]()}finally{if(_d)throw _e;}}JSCompiler_temp=
_arr}if(!(_s=JSCompiler_temp))a:{if(arr){if("string"===typeof arr){_s=_arrayLikeToArray(arr,i);break a}_s=Object.prototype.toString.call(arr).slice(8,-1);"Object"===_s&&arr.constructor&&(_s=arr.constructor.name);if("Map"===_s||"Set"===_s){_s=Array.from(arr);break a}if("Arguments"===_s||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(_s)){_s=_arrayLikeToArray(arr,i);break a}}_s=void 0}if(!(arr=_s))throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
return arr}function _arrayLikeToArray(arr,len){if(null==len||len>arr.length)len=arr.length;for(var i=0,arr2=Array(len);i<len;i++)arr2[i]=arr[i];return arr2}function countsData(_ref){_ref=_slicedToArray(_ref,3);return[{name:"unspecified",value:void 0,count:_ref[2]},{name:"on",value:!0,count:_ref[0]},{name:"off",value:!1,count:_ref[1]}]}Object.defineProperty(exports,"__esModule",{value:!0});exports.RadialChart=void 0;var _react=_interopRequireWildcard(require("module$node_modules$react$index")),d3=
_interopRequireWildcard(require("module$node_modules$d3$dist$d3_node")),_clsx=function(obj){return obj&&obj.__esModule?obj:{"default":obj}}(require("module$node_modules$clsx$dist$clsx"));global=function(_Component){function RadialChart(props){if(!(this instanceof RadialChart))throw new TypeError("Cannot call a class as a function");var _this=_super.call(this,props);_defineProperty(_assertThisInitialized(_this),"divRef",void 0);_defineProperty(_assertThisInitialized(_this),"svg",void 0);_defineProperty(_assertThisInitialized(_this),
"pie",void 0);_defineProperty(_assertThisInitialized(_this),"arc",void 0);_defineProperty(_assertThisInitialized(_this),"initialize",function(){var _this$props=_this.props,radius=_this$props.radius,p=_this$props.innerRadiusProportion,counts=_this$props.counts,d=2*radius;_this$props=_this.pie.padAngle(_this$props.padAngle);var arc=_this.arc.innerRadius(p*radius).outerRadius(radius);p=_this$props(countsData([1,0,0]));var targets=_this$props(countsData(counts));d3.select(_this.divRef.current).append(function(){return _this.svg.attr("height",
d).attr("width",d).attr("viewBox","".concat(-radius," ").concat(-radius," ").concat(d," ").concat(d)).attr("preserveAspectRatio","xMinYMin meet").node()}).selectAll("path.sector-arc").data(p).join("path").classed("sector-arc",!0).attr("data-boolval",function(d){return String(d.data.value)}).attr("d",function(d){return arc(d)}).each(function(d){return d.current=d}).call(function(path){return path.transition().duration(1E3*(1-counts[0]/d3.sum(counts))).ease(d3.easeCubicInOut).tween("data",function(d,
i){var interp=d3.interpolate(d.current,targets[i]);return function(t){return d.current=interp(t)}}).attrTween("d",function(d){return function(){var _arc;return null!==(_arc=arc(d.current))&&void 0!==_arc?_arc:""}})})});_defineProperty(_assertThisInitialized(_this),"updateChart",function(){var _this$props2=_this.props,p=_this$props2.innerRadiusProportion,r=_this$props2.radius,counts=_this$props2.counts;_this$props2=_this.pie.padAngle(_this$props2.padAngle);var arc=_this.arc.innerRadius(r*p).outerRadius(r),
targets=_this$props2(countsData(counts));_this.svg.selectAll("path.sector-arc").transition().duration(350).tween("data",function(d,i){var interp=d3.interpolate(d.current,targets[i]);return function(t){return d.current=interp(t)}}).attrTween("d",function(d){return function(){var _arc2;return null!==(_arc2=arc(d.current))&&void 0!==_arc2?_arc2:""}})});_defineProperty(_assertThisInitialized(_this),"formatTermCount",function(n){if(1E7>n)return _react["default"].createElement("div",{className:"value exact"},
d3.format(",~d")(n));n=d3.format(".2e")(n).split(/[eE]\+?/);var _d3$format$split2=_slicedToArray(n,2);n=_d3$format$split2[0];_d3$format$split2=_d3$format$split2[1];return _react["default"].createElement("div",{className:"value approx"},_react["default"].createElement("span",{className:"tilde"},"~"),_react["default"].createElement("span",{className:"mantissa"},n),_react["default"].createElement("span",{className:"mult-sign"},"×"),_react["default"].createElement("span",{className:"base"},"10"),_react["default"].createElement("sup",
{className:"exponent"},_d3$format$split2))});_this.divRef=_react["default"].createRef();_this.svg=d3.create("svg").classed("chart",!0);_this.arc=d3.arc();_this.pie=d3.pie().sort(null).value(function(d){return d.count});_this.state={};return _this}_inherits(RadialChart,_Component);var _super=_createSuper(RadialChart);_createClass(RadialChart,[{key:"componentDidMount",value:function(){this.initialize()}},{key:"render",value:function(){var _this$props$counts=_slicedToArray(this.props.counts,3),on=_this$props$counts[0],
off=_this$props$counts[1];_this$props$counts=_this$props$counts[2];var nterms=on+off+_this$props$counts,formatPercent=d3.format(".1~%");return _react["default"].createElement("figure",{className:(0,_clsx["default"])("RadialChart",this.props.className)},_react["default"].createElement("div",{className:"chart-container",ref:this.divRef},_react["default"].createElement("div",{className:"center-label"},this.formatTermCount(nterms),_react["default"].createElement("div",{className:"unit"},1===nterms?"term":
"terms"))),_react["default"].createElement("figcaption",{className:"legend"},_react["default"].createElement("div",{className:"icon","data-boolval":"true"}),_react["default"].createElement("div",{className:"value count","data-boolval":"true"},this.formatTermCount(on)),_react["default"].createElement("div",{className:"value percentage","data-boolval":"true"},"(",formatPercent(on/nterms),")"),_react["default"].createElement("div",{className:"label"},"True"),_react["default"].createElement("div",{className:"icon",
"data-boolval":"false"}),_react["default"].createElement("div",{className:"value count","data-boolval":"false"},this.formatTermCount(off)),_react["default"].createElement("div",{className:"value percentage","data-boolval":"true"},"(",formatPercent(off/nterms),")"),_react["default"].createElement("div",{className:"label"},"False"),_this$props$counts?_react["default"].createElement(_react["default"].Fragment,null,_react["default"].createElement("div",{className:"icon","data-boolval":"undefined"}),_react["default"].createElement("div",
{className:"value count","data-boolval":"undefined"},this.formatTermCount(_this$props$counts)),_react["default"].createElement("div",{className:"value percentage","data-boolval":"true"},"(",formatPercent(_this$props$counts/nterms),")"),_react["default"].createElement("div",{className:"label"},"Unspecified")):null))}},{key:"componentDidUpdate",value:function(){this.updateChart()}}]);return RadialChart}(_react.Component);exports.RadialChart=global;_defineProperty(global,"defaultProps",{radius:100,innerRadiusProportion:.8,
padAngle:.001})}
//# sourceMappingURL=module$bfuncs$FunctionSummary.js.map
