shadow$provide.module$bfuncs$VariablesDragDrop=function(global,require,module,exports){function _typeof(obj$jscomp$0){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&"function"===typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};return _typeof(obj$jscomp$0)}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{"default":obj}}function _getRequireWildcardCache(nodeInterop$jscomp$0){if("function"!==
typeof WeakMap)return null;var cacheBabelInterop=new WeakMap,cacheNodeInterop=new WeakMap;return(_getRequireWildcardCache=function(nodeInterop){return nodeInterop?cacheNodeInterop:cacheBabelInterop})(nodeInterop$jscomp$0)}function _extends(){_extends=Object.assign||function(target){for(var i=1;i<arguments.length;i++){var source=arguments[i],key;for(key in source)Object.prototype.hasOwnProperty.call(source,key)&&(target[key]=source[key])}return target};return _extends.apply(this,arguments)}function _createForOfIteratorHelper(o,
allowArrayLike){var it="undefined"!==typeof Symbol&&o[Symbol.iterator]||o["@@iterator"];if(!it){if(Array.isArray(o)||(it=_unsupportedIterableToArray(o))||allowArrayLike&&o&&"number"===typeof o.length){it&&(o=it);var i=0;allowArrayLike=function(){};return{s:allowArrayLike,n:function(){return i>=o.length?{done:!0}:{done:!1,value:o[i++]}},e:function(_e2){throw _e2;},f:allowArrayLike}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var normalCompletion=!0,didErr=!1,err;return{s:function(){it=it.call(o)},n:function(){var step=it.next();normalCompletion=step.done;return step},e:function(_e3){didErr=!0;err=_e3},f:function(){try{if(!normalCompletion&&null!=it["return"])it["return"]()}finally{if(didErr)throw err;}}}}function _unsupportedIterableToArray(o,minLen){if(o){if("string"===typeof o)return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);"Object"===n&&o.constructor&&(n=o.constructor.name);
if("Map"===n||"Set"===n)return Array.from(o);if("Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}}function _arrayLikeToArray(arr,len){if(null==len||len>arr.length)len=arr.length;for(var i=0,arr2=Array(len);i<len;i++)arr2[i]=arr[i];return arr2}function ownKeys(object,enumerableOnly){var keys=Object.keys(object);if(Object.getOwnPropertySymbols){var symbols=Object.getOwnPropertySymbols(object);enumerableOnly&&(symbols=symbols.filter(function(sym){return Object.getOwnPropertyDescriptor(object,
sym).enumerable}));keys.push.apply(keys,symbols)}return keys}function _objectSpread(target){for(var i=1;i<arguments.length;i++){var source=null!=arguments[i]?arguments[i]:{};i%2?ownKeys(Object(source),!0).forEach(function(key){_defineProperty(target,key,source[key])}):Object.getOwnPropertyDescriptors?Object.defineProperties(target,Object.getOwnPropertyDescriptors(source)):ownKeys(Object(source)).forEach(function(key){Object.defineProperty(target,key,Object.getOwnPropertyDescriptor(source,key))})}return target}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||!1;descriptor.configurable=!0;"value"in descriptor&&(descriptor.writable=!0);Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){protoProps&&_defineProperties(Constructor.prototype,protoProps);staticProps&&_defineProperties(Constructor,staticProps);return Constructor}function _inherits(subClass,
superClass){if("function"!==typeof superClass&&null!==superClass)throw new TypeError("Super expression must either be null or a function");subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,writable:!0,configurable:!0}});superClass&&_setPrototypeOf(subClass,superClass)}function _setPrototypeOf(o$jscomp$0,p$jscomp$0){_setPrototypeOf=Object.setPrototypeOf||function(o,p){o.__proto__=p;return o};return _setPrototypeOf(o$jscomp$0,p$jscomp$0)}function _createSuper(Derived){var hasNativeReflectConstruct=
_isNativeReflectConstruct();return function(){var Super=_getPrototypeOf(Derived);if(hasNativeReflectConstruct){var NewTarget=_getPrototypeOf(this).constructor;Super=Reflect.construct(Super,arguments,NewTarget)}else Super=Super.apply(this,arguments);Super=!Super||"object"!==_typeof(Super)&&"function"!==typeof Super?_assertThisInitialized(this):Super;return Super}}function _assertThisInitialized(self){if(void 0===self)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return self}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}function _getPrototypeOf(o$jscomp$0){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(o){return o.__proto__||Object.getPrototypeOf(o)};return _getPrototypeOf(o$jscomp$0)}function _defineProperty(obj,key,
value){key in obj?Object.defineProperty(obj,key,{value,enumerable:!0,configurable:!0,writable:!0}):obj[key]=value;return obj}Object.defineProperty(exports,"__esModule",{value:!0});exports["default"]=void 0;var _react=function(obj,nodeInterop){if(!nodeInterop&&obj&&obj.__esModule)return obj;if(null===obj||"object"!==_typeof(obj)&&"function"!==typeof obj)return{"default":obj};if((nodeInterop=_getRequireWildcardCache(nodeInterop))&&nodeInterop.has(obj))return nodeInterop.get(obj);var newObj={},hasPropertyDescriptor=
Object.defineProperty&&Object.getOwnPropertyDescriptor,key;for(key in obj)if("default"!==key&&Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,key):null;desc&&(desc.get||desc.set)?Object.defineProperty(newObj,key,desc):newObj[key]=obj[key]}newObj["default"]=obj;nodeInterop&&nodeInterop.set(obj,newObj);return newObj}(require("module$node_modules$react$index")),_reactBeautifulDnd=require("module$node_modules$react_beautiful_dnd$dist$react_beautiful_dnd_cjs"),
_clsx=_interopRequireDefault(require("module$node_modules$clsx$dist$clsx")),_RootRef=_interopRequireDefault(require("module$node_modules$$material_ui$core$esm$RootRef$index")),_Button=_interopRequireDefault(require("module$node_modules$$material_ui$core$esm$Button$index")),_DragIndicator=_interopRequireDefault(require("module$node_modules$$material_ui$icons$esm$DragIndicator"));global=function(_Component){function VariablesDragDrop(props){if(!(this instanceof VariablesDragDrop))throw new TypeError("Cannot call a class as a function");
var _this=_super.call(this,props);_defineProperty(_assertThisInitialized(_this),"handleRecompute",function(){_this.props.onChangeCommitted(_this.state.variables.map(function(v){return v.name}));var variables=_this.state.variables.map(function(v,i){return _objectSpread(_objectSpread({},v),{},{index:i})});_this.setState({reordered:!1,variables})});_defineProperty(_assertThisInitialized(_this),"handleReset",function(){_this.setState({variables:_this.props.variables.slice().sort(function(a,b){return a.index-
b.index}),reordered:!1})});_defineProperty(_assertThisInitialized(_this),"handleDragEnd",function(result){document.body.classList.toggle("dragging",!1);if(result.destination){var startIndex=result.source.index,endIndex=result.destination.index;result=Array.from(_this.state.variables);startIndex=result.splice(startIndex,1);var JSCompiler_temp;var JSCompiler_temp$jscomp$0=Array.isArray(startIndex)?startIndex:void 0;if(!JSCompiler_temp$jscomp$0)if(JSCompiler_temp$jscomp$0=startIndex&&("undefined"!==
typeof Symbol&&startIndex[Symbol.iterator]||startIndex["@@iterator"]),null!=JSCompiler_temp$jscomp$0){var _arr=[],_n=!0,_d=!1;try{for(JSCompiler_temp$jscomp$0=JSCompiler_temp$jscomp$0.call(startIndex);!(_n=(JSCompiler_temp=JSCompiler_temp$jscomp$0.next()).done)&&(_arr.push(JSCompiler_temp.value),1!==_arr.length);_n=!0);}catch(err){_d=!0;var _e=err}finally{try{if(!_n&&null!=JSCompiler_temp$jscomp$0["return"])JSCompiler_temp$jscomp$0["return"]()}finally{if(_d)throw _e;}}JSCompiler_temp$jscomp$0=_arr}else JSCompiler_temp$jscomp$0=
void 0;if(!(JSCompiler_temp=JSCompiler_temp$jscomp$0||_unsupportedIterableToArray(startIndex,1)))throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");result.splice(endIndex,0,JSCompiler_temp[0]);endIndex=!1;JSCompiler_temp=Number.NEGATIVE_INFINITY;_e=_createForOfIteratorHelper(result);var _step;try{for(_e.s();!(_step=_e.n()).done;){var index=_step.value.index;if(JSCompiler_temp<index)JSCompiler_temp=
index;else{endIndex=!0;break}}}catch(err){_e.e(err)}finally{_e.f()}_this.setState({variables:result,reordered:endIndex})}});_defineProperty(_assertThisInitialized(_this),"onDragStart",function(){document.body.classList.toggle("dragging",!0)});_this.state={reordered:!1,variables:props.variables};return _this}_inherits(VariablesDragDrop,_Component);var _super=_createSuper(VariablesDragDrop);_createClass(VariablesDragDrop,[{key:"render",value:function(){var _this$props=this.props,className=_this$props.className,
rowHeaders=_this$props.rowHeaders,equalsSign=_this$props.equalsSign;_this$props=this.state;var variables=_this$props.variables;_this$props=_this$props.reordered;return _react["default"].createElement("div",{className:(0,_clsx["default"])(className,"variables-drag-drop")},_react["default"].createElement("div",{className:"columns-container"},_react["default"].createElement("div",{className:"column headers"},rowHeaders.map(function(rowHeader,i){return _react["default"].createElement("div",{key:i,className:"header"},
rowHeader)})),_react["default"].createElement("div",{className:"column equals"},rowHeaders.map(function(_,i){return _react["default"].createElement("div",{key:i,className:"equals-sign"},equalsSign)})),_react["default"].createElement(_reactBeautifulDnd.DragDropContext,{onDragStart:this.onDragStart,onDragEnd:this.handleDragEnd},_react["default"].createElement(_reactBeautifulDnd.Droppable,{droppableId:"dropsy"},function(provided$jscomp$0,snapshot$jscomp$0){return _react["default"].createElement(_RootRef["default"],
{rootRef:provided$jscomp$0.innerRef},_react["default"].createElement("div",{className:"column vars"},variables.map(function(v,i){return _react["default"].createElement(_reactBeautifulDnd.Draggable,{key:v.name,draggableId:v.name,index:i},function(provided,snapshot){var _snapshot$dropAnimati,_snapshot$dropAnimati2;return _react["default"].createElement("div",_extends({className:(0,_clsx["default"])("draggable-var",snapshot.isDragging&&"dragging",snapshot.isDropAnimating&&"drop-animating"),ref:provided.innerRef},
provided.draggableProps,provided.dragHandleProps,{style:_objectSpread(_objectSpread({},provided.draggableProps.style),snapshot.isDropAnimating&&{transition:"all ".concat(null===(_snapshot$dropAnimati=snapshot.dropAnimation)||void 0===_snapshot$dropAnimati?void 0:_snapshot$dropAnimati.curve," ").concat(null===(_snapshot$dropAnimati2=snapshot.dropAnimation)||void 0===_snapshot$dropAnimati2?void 0:_snapshot$dropAnimati2.duration,"s"),boxShadow:"none"})}),_react["default"].createElement("div",{className:"content",
"aria-label":v.name},v.element,_react["default"].createElement(_DragIndicator["default"],{color:"action",fontSize:"small"})))})}),provided$jscomp$0.placeholder))}))),_react["default"].createElement("div",{className:"buttons-container"},_react["default"].createElement(_Button["default"],{disabled:!_this$props,size:"small",onClick:this.handleReset},"Reset"),_react["default"].createElement(_Button["default"],{size:"small",variant:"outlined",disabled:!_this$props,color:"primary",onClick:this.handleRecompute},
"OK")))}}]);return VariablesDragDrop}(_react.Component);exports["default"]=global}
//# sourceMappingURL=module$bfuncs$VariablesDragDrop.js.map
