shadow$provide.module$bfuncs$CoverageTable=function(global,require,module,exports){function _typeof(obj$jscomp$0){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&"function"===typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};return _typeof(obj$jscomp$0)}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{"default":obj}}function _getRequireWildcardCache(nodeInterop$jscomp$0){if("function"!==
typeof WeakMap)return null;var cacheBabelInterop=new WeakMap,cacheNodeInterop=new WeakMap;return(_getRequireWildcardCache=function(nodeInterop){return nodeInterop?cacheNodeInterop:cacheBabelInterop})(nodeInterop$jscomp$0)}function _interopRequireWildcard(obj,nodeInterop){if(!nodeInterop&&obj&&obj.__esModule)return obj;if(null===obj||"object"!==_typeof(obj)&&"function"!==typeof obj)return{"default":obj};if((nodeInterop=_getRequireWildcardCache(nodeInterop))&&nodeInterop.has(obj))return nodeInterop.get(obj);
var newObj={},hasPropertyDescriptor=Object.defineProperty&&Object.getOwnPropertyDescriptor,key;for(key in obj)if("default"!==key&&Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,key):null;desc&&(desc.get||desc.set)?Object.defineProperty(newObj,key,desc):newObj[key]=obj[key]}newObj["default"]=obj;nodeInterop&&nodeInterop.set(obj,newObj);return newObj}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=
props[i];descriptor.enumerable=descriptor.enumerable||!1;descriptor.configurable=!0;"value"in descriptor&&(descriptor.writable=!0);Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){protoProps&&_defineProperties(Constructor.prototype,protoProps);staticProps&&_defineProperties(Constructor,staticProps);return Constructor}function _inherits(subClass,superClass){if("function"!==typeof superClass&&null!==superClass)throw new TypeError("Super expression must either be null or a function");
subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,writable:!0,configurable:!0}});superClass&&_setPrototypeOf(subClass,superClass)}function _setPrototypeOf(o$jscomp$0,p$jscomp$0){_setPrototypeOf=Object.setPrototypeOf||function(o,p){o.__proto__=p;return o};return _setPrototypeOf(o$jscomp$0,p$jscomp$0)}function _createSuper(Derived){var hasNativeReflectConstruct=_isNativeReflectConstruct();return function(){var Super=_getPrototypeOf(Derived);if(hasNativeReflectConstruct){var NewTarget=
_getPrototypeOf(this).constructor;Super=Reflect.construct(Super,arguments,NewTarget)}else Super=Super.apply(this,arguments);Super=!Super||"object"!==_typeof(Super)&&"function"!==typeof Super?_assertThisInitialized(this):Super;return Super}}function _assertThisInitialized(self){if(void 0===self)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return self}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;
if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}function _getPrototypeOf(o$jscomp$0){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(o){return o.__proto__||Object.getPrototypeOf(o)};return _getPrototypeOf(o$jscomp$0)}function _defineProperty(obj,key,value){key in obj?Object.defineProperty(obj,key,{value,enumerable:!0,configurable:!0,writable:!0}):obj[key]=value;return obj}function _createForOfIteratorHelper(o,
allowArrayLike){var it="undefined"!==typeof Symbol&&o[Symbol.iterator]||o["@@iterator"];if(!it){if(Array.isArray(o)||(it=_unsupportedIterableToArray(o))||allowArrayLike&&o&&"number"===typeof o.length){it&&(o=it);var i=0;allowArrayLike=function(){};return{s:allowArrayLike,n:function(){return i>=o.length?{done:!0}:{done:!1,value:o[i++]}},e:function(_e2){throw _e2;},f:allowArrayLike}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var normalCompletion=!0,didErr=!1,err;return{s:function(){it=it.call(o)},n:function(){var step=it.next();normalCompletion=step.done;return step},e:function(_e3){didErr=!0;err=_e3},f:function(){try{if(!normalCompletion&&null!=it["return"])it["return"]()}finally{if(didErr)throw err;}}}}function _slicedToArray(arr,i){var JSCompiler_temp=Array.isArray(arr)?arr:void 0;if(!JSCompiler_temp)if(JSCompiler_temp=arr&&("undefined"!==typeof Symbol&&arr[Symbol.iterator]||arr["@@iterator"]),null==JSCompiler_temp)JSCompiler_temp=
void 0;else{var _arr=[],_n=!0,_d=!1,_s;try{for(JSCompiler_temp=JSCompiler_temp.call(arr);!(_n=(_s=JSCompiler_temp.next()).done)&&(_arr.push(_s.value),!i||_arr.length!==i);_n=!0);}catch(err){_d=!0;var _e=err}finally{try{if(!_n&&null!=JSCompiler_temp["return"])JSCompiler_temp["return"]()}finally{if(_d)throw _e;}}JSCompiler_temp=_arr}if(!(arr=JSCompiler_temp||_unsupportedIterableToArray(arr,i)))throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
return arr}function _unsupportedIterableToArray(o,minLen){if(o){if("string"===typeof o)return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);"Object"===n&&o.constructor&&(n=o.constructor.name);if("Map"===n||"Set"===n)return Array.from(o);if("Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}}function _arrayLikeToArray(arr,len){if(null==len||len>arr.length)len=arr.length;for(var i=0,arr2=Array(len);i<len;i++)arr2[i]=
arr[i];return arr2}function defineShadow(defs,id,specs){var filter=defs.append("filter").attr("id",id);filter.append("feComponentTransfer").attr("result",0).append("feFuncA").attr("type","linear").attr("slope",2E3);var toMerge=specs.map(function(_ref,i){var _ref2=_slicedToArray(_ref,5),dx=_ref2[0],dy=_ref2[1];_ref=_ref2[2];var spread=_ref2[3];_ref2=_ref2[4];var chain=0;i="s".concat(i);spread&&filter.append("feMorphology").attr("in",chain).attr("operator",0<spread?"dilate":"erode").attr("radius",Math.abs(spread)).attr("result",
++chain);filter.append("feOffset").attr("in",chain).call(function(offset){dx&&offset.attr("dx",dx);dy&&offset.attr("dy",dy)}).attr("result",++chain);_ref&&filter.append("feGaussianBlur").attr("in",chain).attr("stdDeviation",_ref).attr("result",++chain);filter.append("feComposite").attr("in",chain).attr("in2",0).attr("operator","out").attr("result",++chain);filter.append("feFlood").attr("flood-color",_ref2);filter.append("feComposite").attr("operator","in").attr("in2",chain).attr("result",i);return i});
filter.append("feMerge").call(function(merge){var _iterator=_createForOfIteratorHelper(toMerge),_step;try{for(_iterator.s();!(_step=_iterator.n()).done;){var _x=_step.value;merge.append("feMergeNode").attr("in",_x)}}catch(err){_iterator.e(err)}finally{_iterator.f()}}).append("feMergeNode").attr("in","SourceGraphic")}function tableScale(n,_ref3){var _ref4=_slicedToArray(_ref3,2);_ref3=_ref4[0];_ref4=_ref4[1];return[Math.abs((_ref4-_ref3)/n),d3.scaleLinear([-.5,n-.5],[_ref3,_ref4])]}function compressedTableScaleBy(data,
pred,normalRange){for(var domain=[-1],range=[-1],len=data.length,count=0,i=0,acc=0,start=null;i<len&&pred(data[i]);)i++;i-1<len&&(domain.push(i-1,i),range.push(-1,0),count++);for(i+=1;i<len;i++){var curr=pred(data[i]);curr&&null===start?start=i:curr||(null!==start?(domain.push(start),range.push(++acc),start<i-1&&(domain.push(i-1),range.push(acc)),start=null):acc++,domain.push(i),range.push(++acc),count++)}null!==start&&(domain.push(start),range.push(acc+1));domain.push(i);range.push(acc+1);return[Math.abs((normalRange[1]-
normalRange[0])/count),d3.scaleLinear(domain,range.map(d3.scaleLinear([-1,acc+1],normalRange)))]}function calcConstants(props){var rowHeight=props.rowHeight,minColumnWidth=props.minColumnWidth,margin=props.margin;props=props.data;var rows=props.rows,terms=props.terms;props=margin.left+margin.right;margin=margin.top+margin.bottom;var rowCount=rows.length,colCount=terms.length,height=margin+rowHeight*rowCount,ret=[{height,contentHeight:margin+rowHeight*rowCount,minWidth:props+minColumnWidth*colCount}];
rows=_createForOfIteratorHelper(rows);var _step2;try{for(rows.s();!(_step2=rows.n()).done;)_step2.value.essential&&rowCount--}catch(err){rows.e(err)}finally{rows.f()}_step2=_createForOfIteratorHelper(terms);var _step3;try{for(_step2.s();!(_step3=_step2.n()).done;)_step3.value.covered&&colCount--}catch(err){_step2.e(err)}finally{_step2.f()}ret.push({height,contentHeight:margin+rowHeight*rowCount,minWidth:props+minColumnWidth*colCount});return ret}Object.defineProperty(exports,"__esModule",{value:!0});
exports["default"]=void 0;var _react=_interopRequireWildcard(require("module$node_modules$react$index")),d3=_interopRequireWildcard(require("module$node_modules$d3$dist$d3_node")),_katex=_interopRequireDefault(require("module$node_modules$katex$dist$katex")),_Grid=_interopRequireDefault(require("module$node_modules$$material_ui$core$esm$Grid$index")),_Switch=_interopRequireDefault(require("module$node_modules$$material_ui$core$esm$Switch$index")),_FormControlLabel=_interopRequireDefault(require("module$node_modules$$material_ui$core$esm$FormControlLabel$index"));
global=function(_Component){function CoverageTable(props){if(!(this instanceof CoverageTable))throw new TypeError("Cannot call a class as a function");var _this=_super.call(this,props);_defineProperty(_assertThisInitialized(_this),"divRef",void 0);_defineProperty(_assertThisInitialized(_this),"recomputeScaleObserver",void 0);_defineProperty(_assertThisInitialized(_this),"constants",void 0);_defineProperty(_assertThisInitialized(_this),"divStyle",void 0);_defineProperty(_assertThisInitialized(_this),
"states",void 0);_defineProperty(_assertThisInitialized(_this),"svg",void 0);_defineProperty(_assertThisInitialized(_this),"allEssentialMessage",void 0);_defineProperty(_assertThisInitialized(_this),"allCoveredMessage",void 0);_defineProperty(_assertThisInitialized(_this),"cutout",void 0);_defineProperty(_assertThisInitialized(_this),"transitions",void 0);_defineProperty(_assertThisInitialized(_this),"initialize",function(){var _this$props=_this.props,margin=_this$props.margin,_this$props$data=_this$props.data,
allPrimesEssential=_this$props$data.allPrimesEssential;_this$props$data=_this$props$data.allTermsCovered;var primeType=_this$props.primeType,termType=_this$props.termType;_this$props=_this$props.rowHeight;var divNode=_this.divRef.current;_this.svg=d3.select(divNode).append("svg").classed("root-svg",!0).attr("preserveAspectRatio","none").call(function(svg){svg.append("defs").call(function(defs){defs.call(defineShadow,"shadow-1",[[0,2,1,-1,"rgba(0,0,0,0.2)"],[0,1,1,0,"rgba(0,0,0,0.14)"],[0,1,3,0,"rgba(0,0,0,0.12)"]]).call(defineShadow,
"shadow-2",[[0,3,1,-2,"rgba(0,0,0,0.2)"],[0,2,2,0,"rgba(0,0,0,0.14)"],[0,1,5,0,"rgba(0,0,0,0.12)"]]);defs.append("mask").attr("id","selected-col-mask").attr("x",0).attr("y",0).call(function(mask){mask.append("rect").attr("fill","white").attr("x",0).attr("y",0).attr("width","100%").attr("height","100%");mask=mask.append("g").classed("cutout-group",!0);_this.cutout={cutoutGroup:mask,cutout:mask.append("rect").classed("cutout",!0).attr("x",0).attr("y",0).attr("height","100%").attr("filter","url(#shadow-1)").attr("fill",
"black"),lastSelectedTerm:null}})});svg=svg.append("g").classed("content",!0);svg.append("g").classed("axes",!0).call(function(axes){axes.append("g").classed("axis",!0).classed("x",!0).attr("transform","translate(0, ".concat(margin.top,")")).append("line").classed("domain",!0).attr("x1",0).attr("x2","100%").attr("y1",0).attr("y2",0);axes.append("g").classed("axis",!0).classed("y",!0).attr("transform","translate(".concat(margin.left,", 0)")).append("line").classed("domain",!0).attr("x1",0).attr("x2",
0).attr("y1",0)});svg.append("g").classed("cols",!0);svg.append("g").classed("rows",!0)});allPrimesEssential?_this.allEssentialMessage=d3.select(divNode).append("div").classed("message",!0).classed("all-essential",!0).classed("visible",!1).text("All prime ".concat(primeType,"s are essential.")):_this$props$data&&(_this.allCoveredMessage=d3.select(divNode).append("div").classed("message",!0).classed("all-covered",!0).classed("visible",!1).style("top",0).style("left","".concat(margin.left,"px")).style("right",
"".concat(margin.right,"px")).style("height","".concat(_this$props,"px")).text("All ".concat(termType,"s covered by essential ").concat(primeType,"s.")));_this.recomputeScaleObserver.observe(divNode)});_defineProperty(_assertThisInitialized(_this),"computeStateFromConstant",function(_ref5,i){var _this$divRef$current$,_this$divRef$current,height=_ref5.height,minWidth=_ref5.minWidth;_ref5=_ref5.contentHeight;var divWidth=null!==(_this$divRef$current$=null===(_this$divRef$current=_this.divRef.current)||
void 0===_this$divRef$current?void 0:_this$divRef$current.getBoundingClientRect().width)&&void 0!==_this$divRef$current$?_this$divRef$current$:0;i=!!i;var _this$props2=_this.props;_this$divRef$current=_this$props2.data;var terms=_this$divRef$current.terms;_this$divRef$current$=_this$divRef$current.rows;var allTermsCovered=_this$divRef$current.allTermsCovered;_this$divRef$current=_this$divRef$current.allPrimesEssential;_this$props2=_this$props2.margin;minWidth=Math.max(minWidth,divWidth);divWidth=
i&&!allTermsCovered?compressedTableScaleBy(terms,function(t){return t.covered},[_this$props2.left,minWidth-_this$props2.right]):tableScale(terms.length,[_this$props2.left,minWidth-_this$props2.right]);terms=_slicedToArray(divWidth,2);divWidth=terms[0];terms=terms[1];_this$divRef$current$=i&&!_this$divRef$current?compressedTableScaleBy(_this$divRef$current$,function(r){return r.essential},[_this$props2.top,_ref5-_this$props2.bottom]):tableScale(_this$divRef$current$.length,[_this$props2.top,height-
_this$props2.bottom]);_this$divRef$current$=_slicedToArray(_this$divRef$current$,2);_this$divRef$current=_this$divRef$current$[0];return{hide:i,xScale:terms,yScale:_this$divRef$current$[1],height,contentHeight:_ref5,width:minWidth,cellWidth:divWidth,cellHeight:_this$divRef$current,translateUpHalfRow:"translate(0, ".concat(-_this$divRef$current/2,")"),translateLeftHalfCell:"translate(".concat(-divWidth/2,",0)")}});_defineProperty(_assertThisInitialized(_this),"computeScales",function(){_this.states=
_this.constants.map(_this.computeStateFromConstant);_this.setState(function(state){return _this.states[+state.hide]})});_defineProperty(_assertThisInitialized(_this),"handleHide",function(hide){_this.setState(_this.states[+hide])});_defineProperty(_assertThisInitialized(_this),"enterRow",function(enter){var _this$state=_this.state,cellHeight=_this$state.cellHeight,yScale=_this$state.yScale,translateUpHalfRow=_this$state.translateUpHalfRow;_this$state=_this.props;var margin=_this$state.margin,selectedPrime=
_this$state.selectedPrime,formatRowHeader=_this$state.formatRowHeader,katexOptions=_this$state.katexOptions;return enter.append("g").each(function(_ref10,i){var essential=_ref10.essential,onClick=_ref10.onClick,onKeyDown=_ref10.onKeyDown;_ref10=_ref10.onKeyUp;essential=d3.select(this).classed("row",!0).classed("essential",essential).classed("selected",i===selectedPrime).attr("opacity",1).attr("transform","translate(0, ".concat(yScale(i),")"));essential.append("rect").classed("row-rect",!0).attr("tabindex",
0).attr("height",cellHeight).attr("width","100%").attr("transform",translateUpHalfRow).attr("mask","url(#selected-col-mask)").on("click",onClick).on("keydown",onKeyDown).on("keyup",_ref10);_katex["default"].render(formatRowHeader(i),essential.append("foreignObject").classed("row-label-container",!0).attr("x",0).attr("y",-cellHeight/2).attr("width",margin.left).attr("height",cellHeight).append("xhtml:div").classed("row-label",!0).style("width","auto").style("text-align","center").style("height","100%").node(),
katexOptions)})});_defineProperty(_assertThisInitialized(_this),"updateRow",function(update){var _this$state2=_this.state,hide=_this$state2.hide,yScale=_this$state2.yScale,translateUpHalfRow=_this$state2.translateUpHalfRow,ty=_this.transitions.ty;_this$state2=_this.props;var selectedPrime=_this$state2.selectedPrime,selectedTerm=_this$state2.selectedTerm,allPrimesEssential=_this.props.data.allPrimesEssential;return update.each(function(_ref12,i){_ref12=_ref12.essential;var sel=d3.select(this).classed("selected",
i===selectedPrime);i=sel.transition(ty).attr("transform","translate(0, ".concat(yScale(i),")"));hide?(null===selectedTerm?i.select(".all-covered.message").transition().duration(300).attr("opacity",1):i.select(".all-covered.message").attr("opacity",0),i.select("rect.row-rect").attr("opacity",_ref12?0:1).attr("transform",_ref12&&!allPrimesEssential?"scale(1, 0)":translateUpHalfRow).attr("tabindex",_ref12?"":0),i.select(".row-label-container").attr("opacity",_ref12?0:1)):(sel.select(".all-covered.message").attr("opacity",
0),i.select("rect.row-rect").attr("opacity",1).attr("tabindex",0).attr("transform",translateUpHalfRow),i.select(".row-label-container").attr("opacity",1))})});_defineProperty(_assertThisInitialized(_this),"enterCell",function(enter){var dotRadius=_this.props.dotRadius,xScale=_this.state.xScale;return enter.append("g").each(function(_ref13,i){_ref13=_ref13.dot;i=d3.select(this).classed("cell",!0).attr("transform","translate(".concat(xScale(i),", 0)")).attr("opacity",1);_ref13&&i.append("circle").classed("dot",
!0).attr("r",dotRadius)})});_defineProperty(_assertThisInitialized(_this),"updateCell",function(update){var _this$state3=_this.state,hide=_this$state3.hide,xScale=_this$state3.xScale,tx=_this.transitions.tx;return update.each(function(_ref15,i){_ref15=_ref15.covered;d3.select(this).transition(tx).attr("transform","translate(".concat(xScale(i),", 0)")).attr("opacity",hide&&_ref15?0:1).select("circle.dot").attr("transform",hide&&_ref15?"scale(0, 0)":"")})});_defineProperty(_assertThisInitialized(_this),
"enterColumn",function(enter){var _this$state4=_this.state,cellWidth=_this$state4.cellWidth,xScale=_this$state4.xScale,contentHeight=_this$state4.contentHeight,translateLeftHalfCell=_this$state4.translateLeftHalfCell;_this$state4=_this.props;var margin=_this$state4.margin,formatColumnHeader=_this$state4.formatColumnHeader,katexOptions=_this$state4.katexOptions;return enter.append("g").each(function(_ref16,i){var term=_ref16.term,covered=_ref16.covered,onClick=_ref16.onClick,onKeyDown=_ref16.onKeyDown;
_ref16=_ref16.onKeyUp;i=d3.select(this).classed("column",!0).classed("covered",covered).attr("transform","translate(".concat(xScale(i),", 0)"));i.append("rect").classed("col-rect",!0).attr("tabindex",0).attr("height",contentHeight).attr("width",cellWidth).attr("transform",translateLeftHalfCell).on("click",onClick).on("keydown",onKeyDown).on("keyup",_ref16);_katex["default"].render(formatColumnHeader(term),i.append("foreignObject").classed("column-label-container",!0).attr("x",0).attr("y",0).attr("width",
cellWidth).attr("height",margin.top).attr("transform",translateLeftHalfCell).append("xhtml:div").classed("column-label",!0).style("width","100%").style("text-align","center").style("position","absolute").style("top","50%").style("transform","translateY(-50%)").node(),katexOptions)})});_defineProperty(_assertThisInitialized(_this),"updateColumn",function(update){var _this$state5=_this.state,hide=_this$state5.hide,xScale=_this$state5.xScale,cellWidth=_this$state5.cellWidth,contentHeight=_this$state5.contentHeight,
translateLeftHalfCell=_this$state5.translateLeftHalfCell;_this$state5=_this.props.data;var allTermsCovered=_this$state5.allTermsCovered,allPrimesEssential=_this$state5.allPrimesEssential;_this$state5=_this.transitions;var tx=_this$state5.tx,ty=_this$state5.ty,selectedTerm=_this.props.selectedTerm,thisCutoutRef=_this.cutout,cutout=thisCutoutRef.cutout,cutoutGroup=thisCutoutRef.cutoutGroup,lastSelectedTerm=thisCutoutRef.lastSelectedTerm;return update.each(function(_ref18,i){var term=_ref18.term;_ref18=
_ref18.covered;var sel=d3.select(this),rect=sel.select("rect.col-rect"),op=hide&&_ref18?0:1;sel.transition(tx).attr("transform","translate(".concat(xScale(i),", 0)")).attr("opacity",op).style("pointer-events",hide&&_ref18?"none":"auto").select(".column-label-container").attr("opacity",op);hide&&!allTermsCovered&&_ref18?rect.attr("tabindex","").transition(tx).attr("transform","scale(0, 1)"):rect.attr("tabindex",0).transition(tx).attr("width",cellWidth).attr("transform",translateLeftHalfCell);allPrimesEssential||
rect.transition(ty).attr("height",contentHeight);term===selectedTerm?(sel.classed("selected",!0),cutoutGroup.attr("transform",sel.attr("transform")).transition(tx).attr("transform","translate(".concat(xScale(i),", 0)")),hide&&_ref18?cutout.attr("transform",rect.attr("transform")).transition(tx).attr("transform","scale(0, 1)"):cutout.attr("width",rect.attr("width")).attr("transform",rect.attr("transform")).transition(tx).attr("width",cellWidth).attr("transform",translateLeftHalfCell),selectedTerm!==
lastSelectedTerm&&(cutoutGroup.append(function(){return cutout.node()}),thisCutoutRef.lastSelectedTerm=selectedTerm)):sel.classed("selected",!1)})});_defineProperty(_assertThisInitialized(_this),"renderTable",function(){var _this$props6=_this.props,data=_this$props6.data;_this$props6=_this$props6.selectedTerm;var svg=_this.svg,_assertThisInitialize=_assertThisInitialized(_this),allEssentialMessage=_assertThisInitialize.allEssentialMessage,allCoveredMessage=_assertThisInitialize.allCoveredMessage;
_assertThisInitialize=_this.cutout.cutoutGroup;var _this$state6=_this.state,hide=_this$state6.hide,width=_this$state6.width,height=_this$state6.height;_this$state6=_this$state6.contentHeight;var tx=svg.transition("tx").duration(300).ease(hide?d3.easeSinIn:d3.easeSinOut),ty=svg.transition("ty").duration(300).ease(hide?d3.easeSinOut:d3.easeSinIn);_this.transitions={tx,ty};svg.attr("viewBox","0 0 ".concat(width," ").concat(height)).attr("height",height).attr("width",width);svg.selectAll("g.y.axis\x3eline.domain").transition(ty).attr("y2",
_this$state6);svg.selectAll("g.cols").selectAll("g.column").data(data.terms,function(d){return d.term}).join(_this.enterColumn,_this.updateColumn);svg.selectAll("g.rows").selectAll("g.row").data(data.rows,function(row){return row.index}).join(_this.enterRow,_this.updateRow).selectAll("g.cell").data(function(row){return row.cols},function(col){return col.term}).join(_this.enterCell,_this.updateCell);if(allEssentialMessage)if(hide)svg.classed("all-hidden",!0).selectAll("g.axis").transition(tx).attr("opacity",
0).on("end",function(){allEssentialMessage.classed("visible",!0)});else allEssentialMessage.classed("visible",!1),svg.classed("all-hidden",!1).selectAll("g.axis").transition(tx).attr("opacity",1);else if(allCoveredMessage)if(hide)tx.on("end",function(){allCoveredMessage.classed("visible",!0)});else allCoveredMessage.classed("visible",!1);_assertThisInitialize.classed("active","number"===typeof _this$props6)});_this.constants=calcConstants(props);_this.divRef=_react["default"].createRef();_this.recomputeScaleObserver=
new ResizeObserver(_this.computeScales);var _margin=props.margin;_this.divStyle={flexBasis:props.data.terms.length*props.minColumnWidth+_margin.left+_margin.right,flexGrow:1,flexShrink:1,overflowX:"auto"};_this.state={hide:!1};return _this}_inherits(CoverageTable,_Component);var _super=_createSuper(CoverageTable);_createClass(CoverageTable,[{key:"render",value:function(){var _this2=this,_this$props7=this.props,primeType=_this$props7.primeType,termType=_this$props7.termType,switchDisabled=this.props.data.noPrimesEssential;
return _react["default"].createElement(_Grid["default"],{container:!0,item:!0,direction:"row",className:this.props.className,spacing:2,onClick:_this$props7.onClick},_react["default"].createElement(_Grid["default"],{item:!0,className:"layout-container",xs:12},_react["default"].createElement("div",{className:"coverage-table-div clicky",ref:this.divRef,style:this.divStyle}),_react["default"].createElement("div",{className:"legend"},_react["default"].createElement(_FormControlLabel["default"],{label:"Hide Essentials",
className:"hide-essentials-switch clicky",control:_react["default"].createElement(_Switch["default"],{checked:this.state.hide,onChange:function(e){return _this2.handleHide(e.target.checked)},disabled:switchDisabled,title:switchDisabled?"No prime implicants are essential.":""})}),_react["default"].createElement("div",{className:"dot"}),_react["default"].createElement("div",{className:"legend-label"},"Covered"),_react["default"].createElement("div",{className:"rect essential"}),_react["default"].createElement("div",
{className:"legend-label"},"Essential prime ",primeType),_react["default"].createElement("div",{className:"rect covered"}),_react["default"].createElement("div",{className:"legend-label"},_react["default"].createElement("span",{style:{textTransform:"capitalize"}},termType)," covered by essential ",primeType))))}},{key:"componentDidMount",value:function(){this.initialize()}},{key:"componentDidUpdate",value:function(){this.renderTable()}},{key:"componentWillUnmount",value:function(){this.recomputeScaleObserver.disconnect()}}]);
return CoverageTable}(_react.Component);_defineProperty(global,"defaultProps",{margin:{top:32,right:0,bottom:0,left:40},rowHeight:32,minColumnWidth:32,dotRadius:8,formatRowHeader:function(i){return"\\imp_{".concat(i+1,"}")},formatColumnHeader:function(i){return"\\term_{".concat(i,"}")}});exports["default"]=global}
//# sourceMappingURL=module$bfuncs$CoverageTable.js.map
