shadow$provide.module$bfuncs$TruthTable=function(global,require,module,exports){function _typeof(obj$jscomp$0){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&"function"===typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};return _typeof(obj$jscomp$0)}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{"default":obj}}function _getRequireWildcardCache(nodeInterop){if("function"!==
typeof WeakMap)return null;var cacheBabelInterop=new WeakMap,cacheNodeInterop=new WeakMap;return(_getRequireWildcardCache=function(nodeInterop){return nodeInterop?cacheNodeInterop:cacheBabelInterop})(nodeInterop)}function _interopRequireWildcard(obj,nodeInterop){if(!nodeInterop&&obj&&obj.__esModule)return obj;if(null===obj||"object"!==_typeof(obj)&&"function"!==typeof obj)return{"default":obj};if((nodeInterop=_getRequireWildcardCache(nodeInterop))&&nodeInterop.has(obj))return nodeInterop.get(obj);
var newObj={},hasPropertyDescriptor=Object.defineProperty&&Object.getOwnPropertyDescriptor,key;for(key in obj)if("default"!==key&&Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,key):null;desc&&(desc.get||desc.set)?Object.defineProperty(newObj,key,desc):newObj[key]=obj[key]}newObj["default"]=obj;nodeInterop&&nodeInterop.set(obj,newObj);return newObj}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=
props[i];descriptor.enumerable=descriptor.enumerable||!1;descriptor.configurable=!0;"value"in descriptor&&(descriptor.writable=!0);Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){protoProps&&_defineProperties(Constructor.prototype,protoProps);staticProps&&_defineProperties(Constructor,staticProps);return Constructor}function _inherits(subClass,superClass){if("function"!==typeof superClass&&null!==superClass)throw new TypeError("Super expression must either be null or a function");
subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,writable:!0,configurable:!0}});superClass&&_setPrototypeOf(subClass,superClass)}function _setPrototypeOf(o,p){_setPrototypeOf=Object.setPrototypeOf||function(o,p){o.__proto__=p;return o};return _setPrototypeOf(o,p)}function _createSuper(Derived){var hasNativeReflectConstruct=_isNativeReflectConstruct();return function(){var Super=_getPrototypeOf(Derived);if(hasNativeReflectConstruct){var NewTarget=_getPrototypeOf(this).constructor;
Super=Reflect.construct(Super,arguments,NewTarget)}else Super=Super.apply(this,arguments);Super=!Super||"object"!==_typeof(Super)&&"function"!==typeof Super?_assertThisInitialized(this):Super;return Super}}function _assertThisInitialized(self){if(void 0===self)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return self}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;
try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}function _getPrototypeOf(o$jscomp$0){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(o){return o.__proto__||Object.getPrototypeOf(o)};return _getPrototypeOf(o$jscomp$0)}function _defineProperty(obj,key,value){key in obj?Object.defineProperty(obj,key,{value,enumerable:!0,configurable:!0,writable:!0}):obj[key]=value;return obj}function computeStateFromProps(props){var _chunkSizeExponent,
f=props.f,arity=props.arity,chunkSizeExponent=props.chunkSizeExponent,size=props.size;props=props.fullySpecified;null!==(_chunkSizeExponent=chunkSizeExponent)&&void 0!==_chunkSizeExponent?_chunkSizeExponent:chunkSizeExponent=TruthTable.sizes[size].chunkSizeExponent;_chunkSizeExponent=f instanceof Int8Array?f:(0,_jsUtils.functionBytes)(f,arity);console.log("arity",arity);chunkSizeExponent=Math.min(arity,chunkSizeExponent);return{values:_chunkSizeExponent,rowsPerChunk:1<<chunkSizeExponent,numChunks:1<<
31-Math.clz32(_chunkSizeExponent.length)-chunkSizeExponent,page:0,functionIndex:props&&5>=arity?(0,_jsUtils.bytesToBigInt)(_chunkSizeExponent,!0):null}}function dataBoolVal(x){switch(x){case 0:return"false";case 1:return"true";case -1:return"undefined";default:return""}}Object.defineProperty(exports,"__esModule",{value:!0});exports["default"]=void 0;var _react=_interopRequireWildcard(require("module$node_modules$react$index")),d3=_interopRequireWildcard(require("module$node_modules$d3$dist$d3_node")),
_clsx=_interopRequireDefault(require("module$node_modules$clsx$dist$clsx")),_Pagination=_interopRequireDefault(require("module$node_modules$$material_ui$lab$esm$Pagination$index")),_jsUtils=require("module$bfuncs$jsUtils"),TruthTable=function(_Component){function TruthTable(props){if(!(this instanceof TruthTable))throw new TypeError("Cannot call a class as a function");var _this=_super.call(this,props);_defineProperty(_assertThisInitialized(_this),"divRef",void 0);_defineProperty(_assertThisInitialized(_this),
"initialize",function(){d3.select(_this.divRef.current).selectAll("svg.chunk").remove()});_defineProperty(_assertThisInitialized(_this),"renderTable",function(){if(_this.divRef.current){var bst=TruthTable.sizes[_this.props.size],sel=d3.select(_this.divRef.current),_this$props=_this.props,arity=_this$props.arity,_this$props$blockSize=_this$props.blockSize,blockSize=void 0===_this$props$blockSize?bst.blockSize:_this$props$blockSize;_this$props$blockSize=_this$props.blockMargin;var blockMargin=void 0===
_this$props$blockSize?bst.blockMargin:_this$props$blockSize;_this$props$blockSize=_this$props.margin;var margin=void 0===_this$props$blockSize?bst.margin:_this$props$blockSize;_this$props$blockSize=_this$props.tickPadding;var tickPadding=void 0===_this$props$blockSize?bst.tickPadding:_this$props$blockSize;_this$props=_this$props.chunksPerPage;bst=void 0===_this$props?bst.chunksPerPage:_this$props;_this$props$blockSize=_this.state;var values=_this$props$blockSize.values;_this$props=_this$props$blockSize.numChunks;
var rowsPerChunk=_this$props$blockSize.rowsPerChunk,page=_this$props$blockSize.page;console.log(values,rowsPerChunk);_this$props$blockSize=arity+1;var width=blockSize*_this$props$blockSize+margin.left+margin.right,height=blockSize*rowsPerChunk+margin.top+margin.bottom,rowsPerPage=bst*rowsPerChunk,y=d3.scaleLinear().domain([0,rowsPerChunk]).range([margin.top,height-margin.bottom]),x$jscomp$0=d3.scaleLinear().domain([0,_this$props$blockSize]).range([margin.left,width-margin.right]),yAxis=function(g,
chunk){return g.attr("transform","translate(".concat(margin.left,", ").concat(blockSize/2,")")).call(d3.axisLeft(y).tickValues(d3.range(0,rowsPerChunk,4)).tickFormat(function(x){return String(page*rowsPerPage+chunk*rowsPerChunk+("number"===typeof x?x:x.valueOf()))}).tickSize(0).tickPadding(tickPadding)).call(function(g){return g.select(".domain").remove()}).call(function(g){return g.append("text").attr("x",-margin.left).attr("y",10).attr("fill","currentColor").attr("text-anchor","start")})};sel.selectAll("svg.chunk").data(d3.range(0,
Math.min(_this$props,bst))).join(function(enter){return enter.append("svg").classed("chunk",!0).attr("width",width).attr("height",height).attr("viewBox","0 0 ".concat(width," ").concat(height)).attr("preserveAspectRatio","xMinYMin meet").each(function(i){d3.select(this).append("g").classed("y-axis",!0).call(yAxis,i)})},function(update){return update.attr("width",width).attr("height",height).attr("viewBox","0 0 ".concat(width," ").concat(height)).attr("preserveAspectRatio","xMinYMin meet").each(function(i){d3.select(this).select("g.y-axis").call(yAxis,
i)})},_this.removeSelection).selectAll(".row").data(function(i){return d3.range(i*rowsPerChunk,(i+1)*rowsPerChunk)}).join(function(enter){return enter.append("g").classed("row",!0).attr("transform",function(_,i){return"translate(0, ".concat(y(i),")")}).each(function(d){var sel=d3.select(this);d=page*rowsPerPage+d;for(var j=0;j<arity;j++)sel.append("rect").classed("datum",!0).attr("data-boolval",0!=(d&1<<arity-j-1)).attr("x",x$jscomp$0(j)+blockMargin).attr("y",blockMargin).attr("width",blockSize-2*
blockMargin).attr("height",blockSize-2*blockMargin);sel.append("rect").classed("datum",!0).classed("output",!0).attr("data-boolval",dataBoolVal(values[d])).attr("x",x$jscomp$0(arity)+blockMargin).attr("y",blockMargin).attr("width",blockSize-2*blockMargin).attr("height",blockSize-2*blockMargin).append("title").text(d)})},function(update){return update.each(function(d){var childs=this.children;d=page*rowsPerPage+d;for(var j=0;j<arity;j++)childs[j].dataset.boolval=String(0!=(d&1<<arity-j-1));childs[arity].dataset.boolval=
dataBoolVal(values[d]);childs[arity].firstElementChild.textContent=String(d)})},_this.removeSelection)}});_defineProperty(_assertThisInitialized(_this),"removeSelection",function(exit){return exit.remove()});_defineProperty(_assertThisInitialized(_this),"changePage",function(event,value){_this.setState({page:value-1})});_this.divRef=_react["default"].createRef();_this.state=computeStateFromProps(props);return _this}_inherits(TruthTable,_Component);var _super=_createSuper(TruthTable);_createClass(TruthTable,
[{key:"componentDidMount",value:function(){this.initialize();this.renderTable()}},{key:"render",value:function(){var _this$props2=this.props,arity=_this$props2.arity,maxArity=_this$props2.maxArity;_this$props2=_this$props2.chunksPerPage;_this$props2=void 0===_this$props2?TruthTable.sizes[this.props.size].chunksPerPage:_this$props2;var _this$state2=this.state,page=_this$state2.page;_this$state2=_this$state2.numChunks;return _react["default"].createElement("div",{className:(0,_clsx["default"])("TruthTable",
this.props.className,this.props.size)},arity>maxArity?_react["default"].createElement("div",{className:"suppressed-message"},"Truth table suppressed for function of more than ",this.props.maxArity," arguments."):_react["default"].createElement(_react["default"].Fragment,null,_this$state2>_this$props2&&_react["default"].createElement(_Pagination["default"],{className:"pagination",page:page+1,count:_this$state2/_this$props2,onChange:this.changePage}),_react["default"].createElement("div",{ref:this.divRef,
className:"chunks"})))}},{key:"componentDidUpdate",value:function(prevProps,prevState,snapshot){prevState=this.props;prevProps.f!==prevState.f||prevProps.arity!==prevState.arity||prevProps.chunkSizeExponent!==prevState.chunkSizeExponent||null==this.props.chunkSizeExponent&&prevState.size!==prevProps.size?(this.initialize(),this.setState(computeStateFromProps(this.props))):this.renderTable()}}]);return TruthTable}(_react.Component);_defineProperty(TruthTable,"defaultProps",{size:"medium",maxArity:16,
fullySpecified:!1});_defineProperty(TruthTable,"sizes",{large:{blockSize:40,blockMargin:4,margin:{top:0,left:40,bottom:0,right:0},tickPadding:8,chunkSizeExponent:4,chunksPerPage:2},medium:{blockSize:26,blockMargin:2,margin:{top:0,left:32,bottom:0,right:0},tickPadding:6,chunkSizeExponent:5,chunksPerPage:2},small:{blockSize:14,blockMargin:1,margin:{top:0,left:32,bottom:0,right:0},tickPadding:4,chunkSizeExponent:6,chunksPerPage:4}});exports["default"]=TruthTable}
//# sourceMappingURL=module$bfuncs$TruthTable.js.map
