importScripts("shared.js");
(function(){
var tF=function(a){if(null!=a&&null!=a.Za)a=a.Za(a);else{var b=tF[$APP.ja(null==a?null:a)];if(null!=b)a=b.j?b.j(a):b.call(null,a);else if(b=tF._,null!=b)a=b.j?b.j(a):b.call(null,a);else throw $APP.Ua("IReversible.-rseq",a);}return a},uF=function(a){return!$APP.oe(a)},vF=function(a){return null!=a},wF=function(a,b){if(null!=a&&null!=a.$c)a=a.$c(a,b);else{var c=wF[$APP.ja(null==a?null:a)];if(null!=c)a=c.B?c.B(a,b):c.call(null,a,b);else if(c=wF._,null!=c)a=c.B?c.B(a,b):c.call(null,a,b);else throw $APP.Ua("ITransientSet.-disjoin!",
a);}return a},xF=function(a){return!0===a},yF=function(a,b){return 0!=(a&1<<b)},zF=function(a,b){return $APP.Ra($APP.ne(a,b))},AF=function(a){a=a instanceof $APP.U?a.sa:null;switch(a){case "TRUE":return $APP.ji;case "FALSE":return $APP.ki;case "NOT":return $APP.li;case "ID":return $APP.hi;case "OR":return $APP.pi;case "NOR":return $APP.oi;case "AND":return $APP.ni;case "NAND":return $APP.mi;case "XOR":return $APP.qi;case "XNOR":return $APP.ri;case "IMP":return $APP.ui;case "NIMP":return $APP.vi;case "CON":return $APP.si;
case "NCON":return $APP.ti;case "EQ":return $APP.Ek;default:throw Error(["No matching clause: ",$APP.q.j(a)].join(""));}},BF=function(a,b){return $APP.Zc(a)||$APP.Zc(b)||zF(function(c){return $APP.ld(b,c)},a)},CF=function(a,b){return $APP.vd(function(c,d){return $APP.p(a.j?a.j(d):a.call(null,d))?c+1:c},0,b)},DF=function(a,b){return $APP.Nb($APP.vd(function(c,d){return $APP.p(a.j?a.j(d):a.call(null,d))?c:wF(c,d)},$APP.Kb(b),b))},EF=function(a,b){var c=$APP.F(a);if($APP.O.B(c,$APP.F(b)))for(var d=0;;){var e=
d>=c;if(e)return e;if(null==$APP.T.B(a,d)||$APP.O.B($APP.T.B(a,d),$APP.T.B(b,d)))d+=1;else return!1}else return!1},FF=function(a){a=$APP.z(a);for(var b=$APP.F(a)-1,c=0;;)if(a){var d=$APP.D(a),e=b-1;c=$APP.p($APP.C(a))?c|1<<b:c;a=d;b=e}else return c},GF=function(a,b){return $APP.vd(function(c,d){var e=$APP.fl<<BigInt(d);a:{d=a-d-1;for(var f=e<<$APP.fl,g=($APP.fl<<e)-$APP.fl<<e;;)if(0<d){var l=f<<$APP.fl;g|=g<<f;--d;f=l}else break a}return c^(c&g)>>e},b,$APP.Dg(0,a,1))},HF=function(a,b){return function f(d,
e){return new $APP.Pd(null,function(){var g=$APP.z(e);if(g){if($APP.gd(g)){for(var l=$APP.Tb(g),m=$APP.F(l),n=$APP.Sd(m),r=0;;)if(r<m){var u=function(){var w=d+r,y=$APP.Tc(l,r);return a.B?a.B(w,y):a.call(null,w,y)}();null!=u&&n.add(u);r+=1}else break;return $APP.Vd(n.chunk(),f(d+m,$APP.Ub(g)))}m=function(){var w=$APP.C(g);return a.B?a.B(d,w):a.call(null,d,w)}();return null==m?f(d+1,$APP.sc(g)):$APP.Ld(m,f(d+1,$APP.sc(g)))}return null},null)}(0,b)},IF=function(a){return $APP.z(HF(function(b,c){return $APP.p($APP.Na.j?
$APP.Na.j(c):$APP.Na.call(null,c))?b:null},a))},JF=function(a){for(var b=$APP.Kb($APP.rg);;){var c=$APP.z(a);if(c)c=$APP.C(c),b=$APP.Jh(c)?$APP.ze.B(b,$APP.C(c)):b,a=$APP.D(a);else return $APP.Nb(b)}},KF=function(a,b){return $APP.Be($APP.p(!1)?function(c){return $APP.Wc(0!=(a&1<<c),$APP.sg([a]))}:$APP.Mi.B(yF,a),$APP.Dg(b-1,-1,-1))},LF=function(a,b){var c=null!=b&&"length"in b?b.length:void 0;var d=31-Math.clz32(c);a:switch(a=a instanceof $APP.U?a.sa:null,a){case "min":a=1;break a;case "max":a=0;
break a;default:throw Error(["No matching clause: ",$APP.q.j(a)].join(""));}a:switch(a){case 1:var e=0;break a;case 0:e=1;break a;default:throw Error(["No matching clause: ",$APP.q.j(a)].join(""));}for(var f=0,g=$APP.Kb($APP.Ae),l=$APP.Kb($APP.Ae);;)if(f<c){var m=$APP.O,n=b[f];$APP.p(m.B?m.B(a,n):m.call(null,a,n))?(m=f+1,g=$APP.ze.B(g,KF(f,d)),f=m):$APP.p(m.B?m.B(e,n):m.call(null,e,n))?f+=1:(m=f+1,l=$APP.ze.B(l,KF(f,d)),f=m)}else return new $APP.X(null,2,5,$APP.Z,[$APP.Nb(g),$APP.Nb(l)],null)},MF=
function(a,b){var c=$APP.Se(a),d=$APP.vg($APP.Dg(0,$APP.F(c),1));return new $APP.X(null,2,5,$APP.Z,[c,function(){return function g(f){return new $APP.Pd(null,function(){for(;;){var l=$APP.z(f);if(l){var m=l;if($APP.gd(m)){var n=$APP.Tb(m),r=$APP.F(n),u=$APP.Sd(r);return function(){for(var y=0;;)if(y<r){var A=$APP.Tc(n,y);$APP.Wd(u,DF(function(G,Q,V,Y,ia,wa,ca,x){return function(H){return EF($APP.T.B(x,H),Q)}}(y,A,n,r,u,m,l,c,d),d));y+=1}else return!0}()?$APP.Vd(u.chunk(),g($APP.Ub(m))):$APP.Vd(u.chunk(),
null)}var w=$APP.C(m);return $APP.Ld(DF(function(y,A,G,Q){return function(V){return EF($APP.T.B(Q,V),y)}}(w,m,l,c,d),d),g($APP.sc(m)))}return null}},null)}(b)}()],null)},NF=function(a,b){var c=$APP.z(b);return c?(c=$APP.C(c),$APP.vd(function(d,e){var f=$APP.R(d,0,null),g=$APP.R(d,1,null),l=a.j?a.j(e):a.call(null,e);return l<g?new $APP.X(null,2,5,$APP.Z,[new $APP.X(null,1,5,$APP.Z,[e],null),l],null):$APP.O.B(l,g)?new $APP.X(null,2,5,$APP.Z,[$APP.$f.B(f,e),g],null):d},new $APP.X(null,2,5,$APP.Z,[new $APP.X(null,
1,5,$APP.Z,[c],null),a.j?a.j(c):a.call(null,c)],null),$APP.sc(b))):null},OF=function(a,b){return $APP.Nb($APP.vd(function(c,d){var e=a.j?a.j(d):a.call(null,d);return $APP.Yd(c,e,$APP.$f.B($APP.T.C(c,e,$APP.Ae),d))},$APP.Kb($APP.ie),b))},PF=function(a,b){return null==b?a:$APP.O.B($APP.mi,$APP.Wh(b))?$APP.Ni.B(a,b):$APP.$f.B(a,b)},QF=function(a){var b=JF(a);return new $APP.X(null,2,5,$APP.Z,[b,$APP.Ni.C($APP.rg,$APP.xe(function(c){return $APP.z(c)&&BF(b,c)}),a)],null)},RF=function(a){var b=$APP.Dg(a-
1,-1,-1);return $APP.Og.B($APP.p(!1)?function(c){return $APP.Wc($APP.Be($APP.Mi.B(yF,c),b),new $APP.k(null,1,[$APP.zk,$APP.vd($APP.db,$APP.Dj,$APP.Pc([c]))],null))}:function(c){return $APP.Be($APP.Mi.B(yF,c),b)},$APP.Dg(0,0|1<<a,1))},SF=function(a){if($APP.p(a)){var b=$APP.T.B($APP.Xc(a),$APP.zk);if($APP.p(b))return b;var c=IF(a);return null==c?$APP.vd($APP.db,$APP.Dj,$APP.Pc([FF(a)])):$APP.vg(function(){return function f(e){return new $APP.Pd(null,function(){for(;;){var g=$APP.z(e);if(g){if($APP.gd(g)){var l=
$APP.Tb(g),m=$APP.F(l),n=$APP.Sd(m);a:for(var r=0;;)if(r<m){var u=$APP.Tc(l,r);u=FF($APP.pe.C($APP.Tg,a,$APP.qj.B(c,u)));n.add(u);r+=1}else{l=!0;break a}return l?$APP.Vd(n.chunk(),f($APP.Ub(g))):$APP.Vd(n.chunk(),null)}n=$APP.C(g);return $APP.Ld(FF($APP.pe.C($APP.Tg,a,$APP.qj.B(c,n))),f($APP.sc(g)))}return null}},null)}(RF($APP.F(c)))}())}return null},TF=function(a,b){for(var c=a,d=b,e=!0;;){if($APP.Zc(c)||$APP.Zc(d))return e;a=$APP.D(c);b=$APP.D(d);e=null==$APP.C(d)?e:$APP.Pk.B(e,function(){var f=
$APP.C(c);return $APP.Ra($APP.C(d))?$APP.ii(f):f}());c=a;d=b}},UF=function(a,b){for(var c=a,d=b,e=!1;;){if($APP.Zc(c)||$APP.Zc(d))return e;a=$APP.D(c);b=$APP.D(d);e=null==$APP.C(d)?e:$APP.Ok.B(e,function(){var f=$APP.C(c);return $APP.p($APP.C(d))?$APP.ii(f):f}());c=a;d=b}},VF=function(a,b){var c=$APP.F(a);return $APP.pe.B($APP.Qk,function(){return function g(e,f){return new $APP.Pd(null,function(){for(var l=e,m=f;;){var n=$APP.z(l);if(n){var r=n;if($APP.gd(r)){var u=$APP.Tb(r),w=$APP.F(u),y=$APP.Sd(w);
return function(){for(var Q=0;;)if(Q<w){var V=$APP.Kc(u,Q),Y=Q+m;$APP.O.B(V,"1")&&$APP.Wd(y,$APP.vd(function(ia,wa,ca,x,H,K,J,N,B,I,M){return function(E,P){return 0!=(H&1<<P)?$APP.Pk.B(E,$APP.Kc(a,M-P-1)):E}}(Q,l,m,V,Y,u,w,y,r,n,c),!0,$APP.Dg(c-1,-1,-1)));Q+=1}else return!0}()?$APP.Vd(y.chunk(),g($APP.Ub(r),m+w)):$APP.Vd(y.chunk(),null)}var A=$APP.C(r),G=m;if($APP.O.B(A,"1"))return $APP.Ld($APP.vd(function(Q,V,Y,ia,wa,ca,x){return function(H,K){return 0!=(ia&1<<K)?$APP.Pk.B(H,$APP.Kc(a,x-K-1)):H}}(l,
m,A,G,r,n,c),!0,$APP.Dg(c-1,-1,-1)),g($APP.sc(r),m+1));A=$APP.sc(r);G=m+1;l=A;m=G}else return null}},null)}(function(){var e=b.toString.call(b,2);return e.padStart.call(e,1<<c,"0")}(),0)}())},WF=function(a,b){return $APP.Be($APP.p(a)?$APP.Pi:$APP.Yk,b)},XF=function(a,b,c){var d=WF(b,$APP.Pc([a,$APP.wi(a)])),e=$APP.R(d,0,null),f=$APP.R(d,1,null),g=function(){var l=new $APP.X(null,2,5,$APP.Z,[$APP.Wh(c),a],null);if($APP.O.B(new $APP.X(null,2,5,$APP.Z,[$APP.ri,$APP.oi],null),l)||$APP.O.B(new $APP.X(null,
2,5,$APP.Z,[$APP.qi,$APP.mi],null),l))return $APP.oe($APP.F(c))?$APP.oe:uF;if($APP.O.B(new $APP.X(null,2,5,$APP.Z,[$APP.ri,$APP.mi],null),l))return uF;if($APP.O.B(new $APP.X(null,2,5,$APP.Z,[$APP.qi,$APP.oi],null),l))return $APP.oe;throw Error(["No matching clause: ",$APP.q.j(l)].join(""));}();return $APP.pe.B(e,function(){for(var l=$APP.sc(c),m=new $APP.X(null,2,5,$APP.Z,[$APP.C(c),$APP.ii($APP.C(c))],null);;){var n=$APP.C(l),r=$APP.ii(n);if($APP.Jh(l))return $APP.se(function(w,y,A,G,Q,V,Y,ia){return function(wa,
ca){wa=$APP.p(ia.j?ia.j(wa):ia.call(null,wa))?G:A;return Y.B?Y.B(ca,wa):Y.call(null,ca,wa)}}(l,m,n,r,d,e,f,g),m);var u=$APP.D(l);m=$APP.Ni.C($APP.Be(function(w,y,A,G,Q,V,Y){return function(ia){return Y.B?Y.B(ia,A):Y.call(null,ia,A)}}(l,m,n,r,d,e,f,g),m),$APP.Og.j(function(w,y,A,G,Q,V,Y){return function(ia){return Y.B?Y.B(ia,G):Y.call(null,ia,G)}}(l,m,n,r,d,e,f,g)),tF(m));l=u}}())},YF=function(a,b){return $APP.T.B($APP.p(b)?$APP.Pi:$APP.Yk,a)},$F=function(a,b,c){var d=YF(a,b),e=YF($APP.oi,b);return $APP.O.B(a,
$APP.Wh(c))?$APP.zd(function m(g,l){return $APP.O.B($APP.oi,$APP.Wh(g))?$APP.O.B($APP.oi,$APP.Wh(l))?ZF.C(function(n){return m(g,n)},e,l):ZF.C(function(n){return d.B?d.B(n,l):d.call(null,n,l)},e,g):$APP.O.B($APP.oi,$APP.Wh(l))?ZF.C(function(n){return d.B?d.B(g,n):d.call(null,g,n)},e,l):d.B?d.B(g,l):d.call(null,g,l)},c):c},aG=function(a,b,c,d){var e=YF($APP.oi,c),f=YF($APP.mi,c);a=a instanceof $APP.U?a.sa:null;switch(a){case "EQ":switch(b=b instanceof $APP.U?b.sa:null,b){case "OR":return b=$APP.zd(f,
d),d=ZF.C($APP.ii,f,d),e.B?e.B(b,d):e.call(null,b,d);case "AND":var g=$APP.C(d);d=$APP.D(d);for(var l=!0;;)if(b=$APP.z(d)){var m=$APP.C(b);b=m;d=$APP.D(d);a=function(){var n=l,r=function(){var w=g,y=$APP.ii(m);return e.B?e.B(w,y):e.call(null,w,y)}(),u=function(){var w=$APP.ii(g),y=m;return e.B?e.B(w,y):e.call(null,w,y)}();return f.C?f.C(n,r,u):f.call(null,n,r,u)}();g=b;l=a}else return l;default:throw Error(["No matching clause: ",$APP.q.j(b)].join(""));}case "NEQ":switch(b=b instanceof $APP.U?b.sa:
null,b){case "AND":return b=$APP.zd(e,d),d=ZF.C($APP.ii,e,d),f.B?f.B(b,d):f.call(null,b,d);case "OR":for(g=$APP.C(d),d=$APP.D(d),l=!1;;)if(b=$APP.z(d))b=m=$APP.C(b),d=$APP.D(d),a=function(){var n=l,r=function(){var w=g,y=$APP.ii(m);return f.B?f.B(w,y):f.call(null,w,y)}(),u=function(){var w=$APP.ii(g),y=m;return f.B?f.B(w,y):f.call(null,w,y)}();return e.C?e.C(n,r,u):e.call(null,n,r,u)}(),g=b,l=a;else return l;default:throw Error(["No matching clause: ",$APP.q.j(b)].join(""));}default:throw Error(["No matching clause: ",
$APP.q.j(a)].join(""));}},bG=function(a,b,c){if($APP.O.B($APP.hi,$APP.Wh(c))){var d=$APP.C(c),e=$APP.Wh(d);return $APP.O.B($APP.hi,e)?$APP.C(d):$APP.O.B($APP.mi,e)?ZF.C($APP.ii,YF($APP.wi(e),b),d):$APP.O.B($APP.oi,e)?ZF.C($APP.ii,YF($APP.wi(e),b),d):$APP.O.B($APP.ni,e)?$APP.pe.B(YF(AF(e),b),d):$APP.O.B($APP.pi,e)?$APP.pe.B(YF(AF(e),b),d):$APP.O.B($APP.bk,e)?aG(AF(e),a,b,d):$APP.O.B($APP.Ek,e)?aG(AF(e),a,b,d):$APP.O.B(null,e)?c:$APP.pe.B(YF(AF(e),b),d)}return c},cG=function(a,b,c){for(;;){var d=$APP.Wh(c),
e=d;if($APP.O.B(null,d))return c;if($APP.O.B($APP.bk,d))return aG(e,a,b,c);if($APP.O.B($APP.hi,d)){e=bG(a,b,c);if($APP.ei($APP.hi,e))return e;e=a;d=b;c=bG(a,b,c);a=e;b=d}else{if($APP.O.B($APP.pi,d))return ZF.C($APP.ii,YF($APP.wi(AF(e)),b),c);if($APP.O.B($APP.mi,d))return c;if($APP.O.B($APP.ri,d))return XF(a,b,c);if($APP.O.B($APP.ti,d))return $APP.Ok.B($APP.C(c),$APP.ii($APP.Rc(c)));if($APP.O.B($APP.oi,d))return c;if($APP.O.B($APP.ui,d))return $APP.Pk.B($APP.C(c),$APP.ii($APP.Rc(c)));if($APP.O.B($APP.vi,
d))return $APP.Ok.B($APP.ii($APP.C(c)),$APP.Rc(c));if($APP.O.B($APP.ni,d))return ZF.C($APP.ii,YF($APP.wi(AF(e)),b),c);if($APP.O.B($APP.si,d))return $APP.Pk.B($APP.ii($APP.C(c)),$APP.Rc(c));if($APP.O.B($APP.Ek,d))return aG(e,a,b,c);if($APP.O.B($APP.qi,d))return XF(a,b,c);throw Error(["No matching clause: ",$APP.q.j(d)].join(""));}}},eG=function(a,b){var c=$APP.wi($APP.oi),d=$APP.Mi.B(dG,$APP.rf([$APP.oi,1,c,2,$APP.hi,3]));return function g(f){for(;;){var l=$APP.oi;var m=a;f=cG(l,m,f);var n=$APP.Wh(f);
l=$APP.p(n)?$APP.pe.B(YF(n,m),$APP.Og.B($APP.Mi.C(cG,l,m),f)):f;if($APP.p(d(l))){if($APP.p(a))switch(m=$APP.Wh(l),m instanceof $APP.U?m.sa:null){case "OR":case "AND":l=$APP.pe.B($APP.Pi.j?$APP.Pi.j(m):$APP.Pi.call(null,m),l)}return l}m=$APP.O;f=$APP.Wh(l);if($APP.p(m.B?m.B($APP.oi,f):m.call(null,$APP.oi,f)))return ZF.C(g,YF($APP.oi,a),l);f=$APP.p(m.B?m.B(c,f):m.call(null,c,f))?$F(c,a,l):l}}(b)},hG=function(a,b){a=MF(a,b);var c=$APP.R(a,0,null);a=$APP.R(a,1,null);a=QF(a);var d=$APP.R(a,0,null),e=$APP.R(a,
1,null);return function l(g){return new $APP.Pd(null,function(){for(;;){var m=$APP.z(g);if(m){if($APP.gd(m)){var n=$APP.Tb(m),r=$APP.F(n),u=$APP.Sd(r);a:for(var w=0;;)if(w<r){var y=$APP.Tc(n,w);y=$APP.Og.B(c,y);u.add(y);w+=1}else{n=!0;break a}return n?$APP.Vd(u.chunk(),l($APP.Ub(m))):$APP.Vd(u.chunk(),null)}u=$APP.C(m);return $APP.Ld($APP.Og.B(c,u),l($APP.sc(m)))}return null}},null)}($APP.z(e)?function(){var g=fG($APP.pe.B($APP.Xk,$APP.Og.B($APP.Mi.B($APP.pe,$APP.Wk),e)));if($APP.O.B($APP.oi,$APP.Wh(g))){var l=
$APP.Be($APP.Mi.B(CF,vF),c);return function r(n){return new $APP.Pd(null,function(){for(;;){var u=$APP.z(n);if(u){if($APP.gd(u)){var w=$APP.Tb(u),y=$APP.F(w),A=$APP.Sd(y);a:for(var G=0;;)if(G<y){var Q=$APP.Tc(w,G);Q=PF(d,Q);A.add(Q);G+=1}else{w=!0;break a}return w?$APP.Vd(A.chunk(),r($APP.Ub(u))):$APP.Vd(A.chunk(),null)}A=$APP.C(u);return $APP.Ld(PF(d,A),r($APP.sc(u)))}return null}},null)}($APP.C(NF(function(n){return $APP.O.B($APP.mi,$APP.Wh(n))?ZF.C(l,gG,n):l.j?l.j(n):l.call(null,n)},g)))}return new $APP.X(null,
1,5,$APP.Z,[PF(d,g)],null)}():new $APP.X(null,1,5,$APP.Z,[d],null))},iG=function(a){return function(){function b(e,f){return postMessage($APP.Fj(new $APP.k(null,2,[$APP.fk,a,$APP.xk,e],null)),$APP.Fj(f))}function c(e){return postMessage($APP.Fj(new $APP.k(null,2,[$APP.fk,a,$APP.xk,e],null)))}var d=null;d=function(e,f){switch(arguments.length){case 1:return c.call(this,e);case 2:return b.call(this,e,f)}throw Error("Invalid arity: "+arguments.length);};d.j=c;d.B=b;return d}()},lG=function(a){$APP.Mk.B?
$APP.Mk.B("worker dispatch event received by worker",jG):$APP.Mk.call(null,"worker dispatch event received by worker",jG);$APP.Mk.j?$APP.Mk.j(a):$APP.Mk.call(null,a);var b=function(){var g=null!=a&&"data"in a?a.data:void 0;if(null!=g&&"task"in g)return g.task}(),c=function(){var g=null!=a&&"data"in a?a.data:void 0;if(null!=g&&"task-id"in g)return g["task-id"]}();try{var d=$APP.T.B(kG,b);if(null==d)throw Error(["Execution error: no such task as ",$APP.q.j(b)].join(""));var e=iG(c);return d.B?d.B(e,
a):d.call(null,e,a)}catch(g){if(g instanceof Object){d=g;$APP.Mk.B?$APP.Mk.B("Error in worker",jG):$APP.Mk.call(null,"Error in worker",jG);e=null!=d&&"name"in d?d.name:void 0;var f=null!=d&&"message"in d?d.message:void 0;return postMessage({type:"error",name:e,message:f,error:d.toString.call(d),task:b,"task-id":c,"worker-id":jG})}throw g;}};$APP.tg.prototype.$c=$APP.ea(19,function(a,b){this.ob=$APP.Pb(this.ob,b);return this});
$APP.oc.prototype.Za=$APP.ea(16,function(){var a=this.ka(null);return 0<a?new $APP.Qc(this,a-1,null):null});$APP.X.prototype.Za=$APP.ea(15,function(){return 0<this.I?new $APP.Qc(this,this.I-1,null):null});$APP.Xe.prototype.Za=$APP.ea(14,function(){return this.start!==this.end?new $APP.Qc(this,this.end-this.start-1,null):null});$APP.of.prototype.Za=$APP.ea(13,function(){return new $APP.oc([this.K,this.key],0,null)});
$APP.eg.prototype.Za=$APP.ea(12,function(){return new $APP.oc([this.K,this.key],0,null)});$APP.dg.prototype.Za=$APP.ea(11,function(){return new $APP.oc([this.K,this.key],0,null)});$APP.jg.prototype.Za=$APP.ea(10,function(){return 0<this.I?$APP.cg(this.tree,!1,this.I):null});$APP.ug.prototype.Za=$APP.ea(9,function(){return 0<$APP.F(this.wb)?$APP.Og.B($APP.Qe,tF(this.wb)):null});
var gG=function gG(a){switch(arguments.length){case 0:return gG.P();case 1:return gG.j(arguments[0]);case 2:return gG.B(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return gG.D(arguments[0],arguments[1],new $APP.oc(c.slice(2),0,null))}};gG.P=function(){return 0};gG.j=function(a){return a};gG.B=function(a,b){return a+b};gG.D=function(a,b,c){return $APP.vd(gG,a+b,c)};
gG.Y=function(a){var b=$APP.C(a),c=$APP.D(a);a=$APP.C(c);c=$APP.D(c);return this.D(b,a,c)};gG.T=2;var ZF=function ZF(a){switch(arguments.length){case 3:return ZF.C(arguments[0],arguments[1],arguments[2]);case 4:return ZF.$(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.q.j(arguments.length)].join(""));}};ZF.C=function(a,b,c){return $APP.z(c)?ZF.$(a,b,function(){var d=$APP.C(c);return a.j?a.j(d):a.call(null,d)}(),$APP.sc(c)):$APP.zd(b,c)};
ZF.$=function(a,b,c,d){return $APP.vd(function(e,f){f=a.j?a.j(f):a.call(null,f);return b.B?b.B(e,f):b.call(null,e,f)},c,d)};ZF.T=4;var dG=function dG(a){switch(arguments.length){case 2:return dG.B(arguments[0],arguments[1]);case 4:return dG.$(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.q.j(arguments.length)].join(""));}};dG.B=function(a,b){return dG.$(a,$APP.mj,-Infinity,b)};
dG.$=function(a,b,c,d){return function l(f,g){var m=$APP.Wh(g);return $APP.p(m)?(m=a.j?a.j(m):a.call(null,m),$APP.p(m)?(f=b.B?b.B(m,f):b.call(null,m,f),$APP.p(f)?$APP.me($APP.Mi.B(l,m),g):f):!1):!0}(c,d)};dG.T=4;var fG=function fG(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return fG.D(arguments[0],1<c.length?new $APP.oc(c.slice(1),0,null):null)};
fG.D=function(a,b){b=null!=b&&(b.G&64||$APP.v===b.ca)?$APP.pe.B($APP.Mh,b):b;b=$APP.T.C(b,$APP.Ak,!0);return eG(b,a)};fG.T=1;fG.Y=function(a){var b=$APP.C(a);a=$APP.D(a);return this.D(b,a)};var mG=function mG(a){switch(arguments.length){case 1:return mG.j(arguments[0]);case 2:return mG.B(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.q.j(arguments.length)].join(""));}};mG.j=function(a){return mG.B(a,null)};
mG.B=function(a,b){a:{var c=$APP.oj.B(a,b);for(b=$APP.rg;;)if($APP.z(c)){var d=OF($APP.Mi.B(CF,xF),c);b:for(var e=$APP.rg,f=$APP.rg,g=d;;){var l=$APP.C(g);if($APP.p(l)){var m=l;l=$APP.R(m,0,null);c:{m=$APP.R(m,1,null);l=$APP.T.B(d,l+1);for(var n=$APP.Kb($APP.Ae),r=$APP.Kb($APP.rg);;){var u=$APP.C(m);if($APP.p(u)){d:for(var w=!1,y=l;;){var A=$APP.C(y);if($APP.p(A)){e:{var G=u;var Q=A,V=$APP.F(G);if($APP.O.B($APP.F(Q),V))for(var Y=0,ia=null;;){if(Y>=V){V=$APP.fd(G)?G:$APP.Se(G);V=$APP.p(ia)?$APP.Tg.C(V,
ia,null):V;G=$APP.p(!1)?$APP.Wc(V,new $APP.k(null,1,[$APP.zk,$APP.Ni.B(SF(G),SF(Q))],null)):V;break e}if($APP.O.B($APP.T.B(G,Y),$APP.T.B(Q,Y)))Y+=1;else{if($APP.p(ia)){G=null;break e}ia=Y;Y+=1}}else G=null}$APP.p(G)?(n=$APP.ze.B($APP.p(w)?n:$APP.ze.B(n,u),A),r=$APP.ze.B(r,G),y=$APP.D(y),w=!0):y=$APP.D(y)}else{n=new $APP.X(null,2,5,$APP.Z,[n,r],null);break d}}u=$APP.R(n,0,null);r=n=$APP.R(n,1,null);m=$APP.D(m);n=u}else{l=0<$APP.F(r)?new $APP.X(null,2,5,$APP.Z,[$APP.Nb(n),$APP.Nb(r)],null):null;break c}}}$APP.p(l)?
(m=l,l=$APP.R(m,0,null),m=$APP.R(m,1,null),e=$APP.Ni.B(e,l),f=$APP.Ni.B(f,m),g=$APP.D(g)):g=$APP.D(g)}else{d=new $APP.X(null,2,5,$APP.Z,[$APP.th(e,c),f],null);break b}}c=$APP.R(d,0,null);d=$APP.R(d,1,null);b=$APP.Ni.B(b,c);c=d}else break a}return hG(b,a)};mG.T=2;var jG,kG=new $APP.k(null,7,["function-bytes",function(a,b){b=null!=b&&"data"in b?b.data:void 0;var c=null!=b&&"args"in b?b.args:void 0;var d=$APP.R(c,0,null);b=$APP.R(d,0,null);d=$APP.R(d,1,null);c=$APP.R(c,1,null);b=$APP.$k.functionBytes(Function(b,d),c);c=null!=b&&"buffer"in b?b.buffer:void 0;c=new $APP.X(null,1,5,$APP.Z,[c],null);return a.B?a.B(b,c):a.call(null,b,c)},"minterms-bytes",function(a,b){b=null!=b&&"data"in b?b.data:void 0;var c=null!=b&&"args"in b?b.args:void 0;var d=$APP.R(c,0,null);
b=$APP.R(d,0,null);d=$APP.R(d,1,null);c=$APP.R(c,1,null);b=$APP.$k.functionBytes({on:b,unspecified:d},c);c=null!=b&&"buffer"in b?b.buffer:void 0;c=new $APP.X(null,1,5,$APP.Z,[c],null);return a.B?a.B(b,c):a.call(null,b,c)},"test-task",function(a,b){b=null!=b&&"data"in b?b.data:void 0;b=null!=b&&"args"in b?b.args:void 0;b=$APP.R(b,0,null);return a.j?a.j(b):a.call(null,b)},"assign-id",function(a,b){a=null!=b&&"data"in b?b.data:void 0;a=null!=a&&"args"in a?a.args:void 0;jG=a=$APP.R(a,0,null);return $APP.Mk.B?
$APP.Mk.B("worker assigned id ",a):$APP.Mk.call(null,"worker assigned id ",a)},"min-sops",function(a,b){b=null!=b&&"data"in b?b.data:void 0;var c=null!=b&&"args"in b?b.args:void 0;b=$APP.R(c,0,null);c=$APP.R(c,1,null);$APP.Mk.B?$APP.Mk.B("minsops bitbytes: ",c):$APP.Mk.call(null,"minsops bitbytes: ",c);b=$APP.Og.B($APP.Mi.C(ZF,$APP.Mi.B(TF,b),$APP.Ok),$APP.pe.B(mG,LF($APP.Hk,c)));return a.j?a.j(b):a.call(null,b)},"min-poss",function(a,b){b=null!=b&&"data"in b?b.data:void 0;var c=null!=b&&"args"in
b?b.args:void 0;b=$APP.R(c,0,null);c=$APP.R(c,1,null);$APP.Mk.B?$APP.Mk.B("minposs bitbytes: ",c):$APP.Mk.call(null,"minposs bitbytes: ",c);b=$APP.Og.B($APP.Mi.C(ZF,$APP.Mi.B(UF,b),$APP.Pk),$APP.pe.B(mG,LF($APP.Dk,c)));return a.j?a.j(b):a.call(null,b)},"zhegalkin-polynomial",function(a,b){b=null!=b&&"data"in b?b.data:void 0;var c=null!=b&&"args"in b?b.args:void 0;b=$APP.R(c,0,null);c=$APP.R(c,1,null);c=null==c?null:["0b",$APP.q.j(c)].join("");c=null==c?null:BigInt(c);c=null==c?null:GF($APP.F(b),c);
b=null==c?null:VF(b,c);return a.j?a.j(b):a.call(null,b)}],null);try{$APP.Mk.j?$APP.Mk.j("worker created"):$APP.Mk.call(null,"worker created");var TG=self;TG.addEventListener.call(TG,"message",lG);$APP.Mk.j?$APP.Mk.j(self):$APP.Mk.call(null,self)}catch(a){throw console.error("An error occurred when calling (bfuncs.worker/init)"),a;};
}).call(this);